/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴、人民當家做主
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],
    "   Blobmoji": "Blobmoji",
    "   EmojiTwo": "EmojiTwo",
    "   Fluent Emoji": "Fluent Emoji",
    "   Fluent Emoji Mono": "Fluent Emoji Mono",
    "   Noto Color Emoji": "Noto Color Emoji",
    "   Noto Emoji Mono": "Noto Emoji Mono",
    "   OpenMoji Black": "OpenMoji Black",
    "   OpenMoji": "OpenMoji",
    "   OpenSans+Noto": "OpenSans+Noto",
    "   System default": "系统默认",
    "   Twemoji": "Twemoji",
    "'To tame magical beasts you must begin with the ordinary', he says.": "'要驯服魔法兽，你必须从平凡开始，'他说道。",
    "A small corner beneath the stairs of your Master's domicile.": "你导师住所楼梯下的一个小角落。",
    "A small wooden chest.": "一个小木箱。",
    "Ablative Barrier": "烧蚀护盾",
    "Alcove": "壁龛",
    "Barrier": "护盾",
    "Bed": "床",
    "Bed, Furniture": "床，家具",
    "Cot": "行军床",
    "Furniture Unlocked: cot": "已解锁家具：行军床",
    "Furniture Unlocked: iron chest": "已解锁家具：铁箱",
    "Furniture Unlocked: small chest": "已解锁家具：小木箱",
    "Goodbye hayloft.": "再见了，干草棚。",
    "Holds water for washing yourself and other some such.": "盛水供你洗漱和其他用途。",
    "Iron Chest": "铁箱",
    "Moving In": "搬入",
    "Pets": "宠物",
    "Restores much quicker if you are out of combat": "脱离战斗后恢复速度大幅提升",
    "Slightly better than sleeping on the floor.": "比睡地板略好一些。",
    "Small Chest": "小木箱",
    "The circle's ward shields you from harm.": "结界护盾保护你免受伤害。",
    "Treasure chest.": "宝箱。",
    "Turns out mana really does grow on trees.": "原来魔力真的是从树上长出来的。",
    "Watersource": "水源",
    "Wizard's basic harm prevention measure": "巫师的基础伤害防护措施",
    "Workspace": "工作台",
    "ablative barrier": "烧蚀护盾",
    "animal handling": "动物驯养",
    "crafting": "制作",
    "'Kind and selfless acts can shine a light in the darkest of places.'\n\n➢ Virtue amount is generally granted by actions tagged as either 'Good Acts' or 'Virtuous Acts', with you being able to check your virtue score in the Player Tab.\nSome of the best ways to earn virtue in the early game is through Tend Animals, unlocked after Graduation, and Treat Ailments, unlocked via the Anatomy skill as a Neophyte.\nAs an apprentice, simply performing errands and doing chores for your master will provide some virtue however, this source is finite as after their final improvement they will only provide gold.\n\n➢ Sufficient amounts of virtue will either automatically grant or unlock the ability to select good moralities which boost your light magic at the expense of shadow magic.\nThese good moralities are necessary for unlocking all the good classes.\n\n➢ With high enough virtue, you will be prevented from performing 'Evil Acts' and 'Vile Acts' altogether and unable to cast the strongest draining shadow spells.\nSuch restrictions generally begin from the 'Scrupulous' level of good morality.\n\n➢ The progression of good moralities are as follows:\n• Decent - Automatically granted - Have a virtue score of 90 while having less than 200 evil. Your virtue must exceed your evil by 90.\n• Respectable - Automatically granted - Have a virtue score of 375 while having less than 100 evil. Your virtue must exceed your evil by 250.\n• Virtuous - Automatically granted - Have a virtue score of 750 while having less than 50 evil. Your virtue must exceed your evil by 750. Requires Tier 0.\n• Scrupulous - Have a virtue score of 1500 while having no evil. Requires Tier 1.\n• Incorruptible - Have a virtue score of 3000 while having no evil. Requires Tier 3.\n• Benevolent - Requires Tier 4. Never earned the 'Wicked' morality trait. (Check the 'Evil' glossary to see how to avoid it.)\n\n➢ It is possible to abandon virtue and become evil as long as you are not Incorruptible.":
"'善良无私的行为能在最黑暗的地方点亮光芒。'\n\n➢ 美德值通常通过被标记为'善行'或'美德行为'的行动获得，你可以在玩家面板中查看自己的美德值。\n游戏早期获取美德的最佳方式是通过'照料动物'（毕业后解锁）和'治疗疾病'（通过解剖学技能以新手身份解锁）。\n作为学徒，仅仅为主人跑腿和做家务也能获得一些美德，但这种方式是有限的，因为在最终提升后，这些行为只会提供金币。\n\n➢ 足够的美德值将自动授予或解锁选择善良道德的能力，这些道德会增强你的光明魔法，但以削弱暗影魔法为代价。\n这些善良道德是解锁所有善良职业的必要条件。\n\n➢ 当美德值足够高时，你将完全无法执行'邪恶行为'和'卑劣行为'，也无法施放最强力的暗影吸取法术。\n此类限制通常从'审慎'级别的善良道德开始生效。\n\n➢ 善良道德的 progression 如下：\n• 端正 - 自动获得 - 美德值达到90且邪恶值低于200。美德值需超过邪恶值90点。\n• 可敬 - 自动获得 - 美德值达到375且邪恶值低于100。美德值需超过邪恶值250点。\n• 美德 - 自动获得 - 美德值达到750且邪恶值低于50。美德值需超过邪恶值750点。需要阶位0。\n• 审慎 - 美德值达到1500且无邪恶值。需要阶位1。\n• 清廉 - 美德值达到3000且无邪恶值。需要阶位3。\n• 仁慈 - 需要阶位4。从未获得过'邪恶'道德特质。（查看'邪恶'词条了解如何避免。）\n\n➢ 只要你不是'清廉'级别，就有可能放弃美德并堕入邪恶。",
    "'You're above this illusion of choice.'\n\n➢ Neutrality is represented by various morality options that require you to strike a balance between Virtue and Evil.\n\n➢ The first shared step in this path is the Vow of Neutrality, which requires you to be :\n• Either Decent and Immoral, or neither.\n• Either Respectable and Wicked, or neither.\n• Either Virtuous and Vile, or neither.\n• Have graduated from Apprenticeship\nYou can learn more about the mentioned moralities in the 'Good' and 'Evil' glossary entries.\n\n➢ It then splits into: 1) The Detached path - which weakens both Light and Shadow to specialize in Nature and Spirit, eventually losing access to all Good, Virtuous, Evil and Sinister Acts, and 2) The Equilibrium path - which excels at both Light and Shadow, maintaining the full spectrum of actions.\nThe progression of the Detached path is as follows:\n• Detached - Be Neutral. Be neither Vile nor Virtuous. Have 200 or less Virtue. Have 200 or less Evil. Requires Tier 1.\n• Amoral - Be neither Wicked nor Respectable. Have 200 or less Virtue. Have 200 or less Evil. Requires Tier 3.\n\nThe progression of the Equilibrium path is as follows:\n• Balanced - Be Neutral. Be both Wicked and Respectable. Have 350 Virtue. Have 350 Evil. Requires Tier 1.\n• In Equilibrium - Be both Vile and Virtuous. Have 750 Virtue. Have 750 Evil. Requires Tier 3.\n\nAfter becoming either Amoral or In Equilibrium, you will get to specialize in either Spirit or Nature at Tier 4.\n\n➢ It is possible to abandon the Vow of Neutrality, but only if you are Neutral. Gaining another morality in either branch of Neutrality will no longer allow abandonment.":
"'你已超越这种选择的幻象。'\n\n➢ 中立由各种道德选项代表，要求你在美德与邪恶之间取得平衡。\n\n➢ 这条道路的第一步是'中立誓言'，要求你满足以下条件：\n• 要么是'端正'且'不道德'，要么两者都不是。\n• 要么是'可敬'且'邪恶'，要么两者都不是。\n• 要么是'美德'且'卑劣'，要么两者都不是。\n• 已从学徒期毕业\n你可以在'善良'和'邪恶'词条中了解更多关于上述道德的信息。\n\n➢ 此后分为两条路径：\n1）超然之路 - 削弱光明和暗影以专精自然与灵性，最终失去所有善良、美德、邪恶和险恶行为；\n2）均衡之路 - 同时精通光明和暗影，保留完整的行为谱系。\n\n超然之路的 progression 如下：\n• 超然 - 保持中立。既非卑劣也非美德。美德值200或以下。邪恶值200或以下。需要阶位1。\n• 非道德 - 既非邪恶也非可敬。美德值200或以下。邪恶值200或以下。需要阶位3。\n\n均衡之路的 progression 如下：\n• 平衡 - 保持中立。同时具备邪恶和可敬。美德值350。邪恶值350。需要阶位1。\n• 均衡态 - 同时具备卑劣和美德。美德值750。邪恶值750。需要阶位3。\n\n在成为'非道德'或'均衡态'后，你将在阶位4时选择专精灵性或自然。\n\n➢ 可以放弃'中立誓言'，但仅限于你保持中立时。在中立的任一分支中获得其他道德后将不再允许放弃。",
    "After taking your savings, your new master grants you a small nook under the stairs.":
"在收走你的积蓄后，你的新导师允许你住在楼梯下的一个小角落里。",
    "Master has offered you one of his prized avians to practice falconry. It barely looks fit to be a messenger.":
"导师给了你一只他珍视的猛禽来练习鹰猎术。但它看起来连当信使都不够格。",
    "The handwriting of an uneducated ragamuffin like you is no good for penning magic texts. Master ordered writing supplies for you to practice every stroke.":
"像你这种没受过教育的流浪儿，字迹根本不够格书写魔法文本。导师订购了书写用具，让你练习每一笔。",
    "When first asked to write your name, you produced a script not yet known to man.":
"当第一次被要求写下自己的名字时，你写出了人类尚未知晓的文字。",
    "Whilst seeing your reflection, an understanding of flow and stagnation dawns.":
"看着自己的倒影，你开始领悟流动与停滞的含义。",
    "Your master handed you a flowerpot and some seeds. Harmony with nature begins with a green thumb.":
"你的导师递给你一个花盆和一些种子。与自然的和谐始于一双绿手指。",
    "'Dark and selfish deeds follow you, leaving a stain on your soul.'\n\n➢ Evil amount is generally granted by actions tagged as either 'Evil Acts' or 'Vile Acts', with you being able to check your evil score in the Player Tab.\nSome of the best ways to earn evil in the early game is through Arcane Thievery, unlocked via the Trickery skill, and Murder, unlocked via the Anatomy and Umbramancy skills.\n\n➢ Sufficient amounts of evil will either automatically grant or unlock the ability to select evil moralities which boost your shadow magic at the expense of light magic.\nThese evil moralities are necessary for unlocking many of the evil classes.\n\n➢ With high enough evil, you will be prevented from performing 'Good Acts' and 'Virtuous Acts' altogether and unable to cast the stronger light healing spells.\nSuch restrictions generally begin from the 'Sinister' level of evil morality.\n\n➢ The progression of evil moralities are as follows:\n• Immoral - Automatically granted - Have an evil score of 5.\n• Wicked - Automatically granted - Have an evil score of 250.\n• Vile - Automatically granted - Have an evil score of 500 or Graduate via Slaying your Master. Requires Tier 0.\n• Sinister - Have an evil score of 1000. Requires Tier 1.\n• Irredeemable - Have an evil score of 2000. Requires Tier 3.\n• Malevolence - Requires Tier 4. Never earned the 'Respectable' morality trait. (Check the 'Virtue' glossary to see how to avoid it.)\n\n➢ It is possible to back out of evil and become virtuous as long as you are not Irredeemable.": "'黑暗自私的行径如影随形，在你的灵魂上留下污点。'\n\n➢ 邪恶值通常通过标记为'恶行罪孽'或'邪秽行为'的行动获得，你可以在玩家面板中查看你的邪恶值。\n前期获取邪恶的最佳方式包括：通过'诡术'技能解锁的'奥术窃术'，以及通过'解剖术'和'暗影术'技能解锁的'谋杀'。\n\n➢ 足够的邪恶值将自动授予或解锁选择邪恶道德的能力，这些道德将以光之魔法为代价增强你的暗影魔法。\n这些邪恶道德是解锁众多邪恶职业的必要条件。\n\n➢ 当邪恶值足够高时，你将完全无法执行'善行义举'和'美德行为'，也无法施展更强大的光系治愈法术。\n此类限制通常从'阴邪'级别的邪恶道德开始。\n\n➢ 邪恶道德的晋升路径如下：\n• 悖德 - 自动获得 - 邪恶值达到5。\n• 极恶 - 自动获得 - 邪恶值达到250。\n• 邪秽 - 自动获得 - 邪恶值达到500或通过弑师毕业。需要阶级0。\n• 阴邪 - 邪恶值达到1000。需要阶级1。\n• 不可救赎 - 邪恶值达到2000。需要阶级3。\n• 恶意 - 需要阶级4。从未获得过'可敬'道德特质。（查看'善良'词条了解如何避免获得。）\n\n➢ 只要尚未达到'不可救赎'级别，你仍有可能摆脱邪恶、走向善良。",
    "➢ Focus consumes mana to grant skill experience. If a skill has no other skill rate boosts specific to itself, focus increases the speed of training it by ~40% if it is permanently active.\n\n➢ If you have multiple action slots and use them to train multiple skills simultaneously, only the topmost skill in your action list will be affected by Focus.\n\n➢ It's recommended to toggle on Autofocus by clicking it above your actions, for the sake of your wrist and as its mana cost quickly becomes negligible.": "➢ 专注消耗法力来获得技能经验。如果某项技能没有其他专属的技能速率加成，在永久激活专注的情况下，训练速度可提升约40%。\n\n➢ 如果你拥有多个行动槽位并用于同时训练多项技能，只有行动列表中最顶部的技能会受到专注效果影响。\n\n➢ 为了你的手腕着想，建议点击行动上方的'自动专注'将其开启，因其法力消耗很快就会变得微不足道。",
    "➢ Tasks refer to any non-upgrade action which your wizard can perform in the Main Tab.\n\n➢ Tasks can either be instant or have a defined length. Tasks with a defined length take up an action slot and are coloured yellow.\n\n➢ For the sake of your wrist, you can massively reduce the number of times you need to click instant tasks by holding Enter after performing it once to do it twenty times a second.\n\n➢ The main limiting factor for tasks is your wizard's stamina.\nFor this reason, it is highly recommended to make 'Aquamancy' and 'Aeromancy' some of your first skill purchases, as their combination unlocks stamina generating upgrades.": "➢ 任务指的是你的巫师可以在主面板中执行的任何非升级行动。\n\n➢ 任务可以是即时完成的，也可以有固定的持续时间。有固定持续时间的任务会占用一个行动槽位，并以黄色标示。\n\n➢ 为了你的手腕着想，执行一次即时任务后按住回车键，可以以每秒二十次的速度重复执行，大幅减少点击次数。\n\n➢ 任务的主要限制因素是巫师的耐力。\n因此，强烈建议将'控水术'和'御风术'作为首批技能购买，因为它们的组合可以解锁耐力生成升级。",
    "➢ Tasks which consume an action slot will attempt to perpetually perform themselves ad infinitum however, what happens when one such task can no longer be sustained?\n\n➢ Waiting Tasks refer to those tasks which were forced out of your action slot. They will attempt to take up your action whenever a vacancy is created.\n\n➢ The total number of Waiting Tasks you can have is defined by your total number of action slots + 5. Any further additions to the list will cause an older waiting task to be pushed out.\n\n➢ You can see your Waiting Tasks in the Activities popup menu which is the rightmost button above your actions.": "➢ 消耗行动槽位的任务会尝试无限地自行持续执行，但当这样的任务无法再维持时会发生什么？\n\n➢ 待执行任务指的是那些被强制移出行动槽位的任务。它们会在有空位时尝试重新占据你的行动槽位。\n\n➢ 你最多可拥有的待执行任务数量由你的行动槽位总数 + 5 决定。此后若再添加新任务，列表中最旧的待执行任务将被挤出。\n\n➢ 你可以在行动上方的最后一个按钮'活动'弹窗菜单中查看你的待执行任务。",
    "A good apprentice knows there are 30 hours to the day.": "好学徒都知道一天有30个小时。",
    "A tiny glowing candle.": "一根微弱的发光蜡烛。",
    "Candle": "蜡烛",
    "Continue working even while idle.": "即使闲置时也继续工作。",
    "Essential for developing wizardly defenses.": "对提升巫师防御至关重要。",
    "Game Mechanic, Glossary Entry": "游戏机制、术语词条",
    "Game Mechanic, Skill, Glossary Entry": "游戏机制、技能、术语词条",
    "Game Mechanic, Tasks, Glossary Entry": "游戏机制、任务、术语词条",
    "Magic Circle": "魔法法阵",
    "Mana Energies, Prismatic": "虹彩魔力",
    "Raw magical energy.": "原始的魔法能量。",
    "Wardsource": "屏障之源",
    "Wax Candle": "黄蜡蜡烛",
    "You no take candle!": "不准拿蜡烛！",
  '🛠️Evil':'🛠️邪恶',
  '🛠️Focus':'🛠️专注',
  '🛠️Neutrality':'🛠️中立',
  '🛠️Skills & Arcana':'🛠️技能与奥术秘能',
  '🛠️Tasks':'🛠️任务',
  '🛠️Virtue':'🛠️善良',
  '🛠️Waiting Tasks':'🛠️待执行任务',
  'tasks':'任务',
  'You are turning out to be an upstanding spellcaster.':'你正逐渐成长为一名正直的施法者。',
  	"A measure of reputation. Found a Wizard's Hall to learn more.":"一种声望指标。找到巫师殿堂可了解更多。",
	"Apprentice to a notable wizard.":"知名巫师的学徒。",
	"Carry more scrolls.":"携带更多卷轴。",
	"Decent":"尚可",
	"Morality":"道德",
	"Satchel":"挎包",
	'🧙🏻Equipment🧙🏻':'🧙🏻装备🧙🏻',
	'Changes made from this popup are temporary and only affect the current tab.':'从此弹窗所做的更改是临时的，仅影响当前标签页。',
	'Back:':'背部:',
	'Chest:':'胸部:',
	'Emojify!':'表情化!',
	'Feet:':'脚部:',
	'Go to options':'前往选项',
	'Hands:':'手部:',
	'Head:':'头部:',
	'Inventory':'背包',
	'Main hand:':'主手:',
	'Move in':'搬入',
	'No space remaining. Sell items or find a new Home.':'空间不足。出售物品或寻找新家。',
	'Read help':'阅读帮助',
	'satchel':'挎包',
	'Shins:':'小腿:',
	'Size adj:':'尺寸调整:',
	'Trinket:':'饰品:',
	'View original':'查看原文',
	'Waist:':'腰部:',
	'Arcana: 5/5':'奥秘: 5/5',
	'exp: 1 / 58':'经验: 1 / 58',
	'herbalism':'草药学',
	'languages':'语言学',
	'Max Herbs: 2':'最大草药: 2',
	'Nothing is more important to a wizard than the depth of their lore.':'对巫师来说，没有什么比学识的深度更重要。',
	'Plantsource':'植物之源',
	'Restless Nights':'不眠之夜',
	'School Of Magic, Skill':'魔法学派，技能',
	'Skill':'技能',
	'Train':'训练',
	'wax candle':'蜡烛',
	'Activity Skillprogress: 0.02':'活动技能进度: 0.02',
	'Books and scrolls are written in many obscure languages. Learn as many as possible.':'书籍和卷轴用许多晦涩的语言写成。尽可能多地学习。',
	'Converter':'转换器',
	'Converter Status':'转换器状态',
	'Converters':'转换器',
	'Displays all converters, their inputs, and their output effects.':'显示所有转换器、它们的输入及输出效果。',
	'Does not display "mod" outputs.':'不显示“模组”输出。',
	'Quicken your skills with magic energy.':'用魔力加速你的技能。',
	'Resources':'资源',
	'Total Inputs':'总输入',
	'Total Outputs':'总输出',
	'Latticed shelves for easy scroll storage.':'方便存放卷轴的格子架。',
'Max Scrolls: 15':'最大卷轴数: 15',
'Scroll Rack':'卷轴架',
    //日志章节内容
    'Prologue':'序章',
    'An idle waif with no prospects to speak of...':'一个无所事事的流浪儿，毫无前途可言……',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Achievement Gotten!": "成就达成!",
    "On": "打开",
    "Off": "关闭",
	//资源tags
	"gemimbue": "灌注宝石",
	"magicgems": "魔法宝石",
	"prismatic": "棱柱",
	"prismaticgems": "棱柱宝石",
	"elementalgems": "元素宝石",
	"element": "元素",
	"elemental": "元素知识",
	"primordialgems": "原始宝石",
	"primordial": "原始",
	"elementalrunes": "元素符文",
	"primaticrunes": "棱柱符文",
	"primordialrunes": "原始符文",
	"manas": "法力能量",
	"bed": "床",
	"t_pets": "宠物",
	"pets": "宠物",
	"workspace": "工作区",
	"furniture": "家具",
	"shadowsource": "暗影源泉",
	"spiritsource": "精神源泉",
	"plantsource": "植物源泉",
	"naturesource": "自然源泉",
	"firesource": "火源泉",
	"airsource": "风源泉",
	"watersource": "水源泉",
	"earthsource": "地源泉",
	"lightsource": "光源泉",
	"potsource": "药剂源泉",
	"starsource": "星空源泉",
	"enchantsource": "附魔源泉",
	"weavesource": "编织源泉",
	"timesource": "时间源泉",
	"tricksource": "诡计源泉",
	"stables": "马棚",
	"prison": "监狱",
	"armssource": "军备源泉",
	"outdoors": "户外",
	"patron": "赞助",
	"t_ritual": "仪式",
	"ritual": "仪式",
	"poison": "毒",
	"herb": "草药",
	"reagent": "试剂",
	"t_runes": "符石",
	"skill": "技能",
	"t_school": "学派",
	"school": "学派",
	"stress": "压力",
	"t_rest": "休息",
	"rest": "休息",
	"book": "典籍",
	"steed": "骏马",
	"candle": "蜡烛",
	"t_hall": "殿堂",
	"hall": "殿堂",
	"familiar": "魔宠",
	"magic": "魔法",

	//药剂名：
	"sip of gold": "财富药剂",
	"drip of mana": "生命分流",
	"echoing flask": "回声药水",
	"god's blood": "神之血液",
	"godspeed": "神速药剂",
	"healing potion": "治疗药水",
	"phial of skillfulness": "学识药水",
	"philter of clarity": "灵感药水",
	"potion of bull's tenacity": "牛的力量",
	"potion of monster's stamina": "怪物级耐力药水",
	"remedy": "十全大补抗性药",
	"tincture of limberness": "麻痹解除",
	"adamant salve": "合金药剂",
	"portion of waterbreathing": "水下呼吸药剂",
	'': '',
	
	//药水说明：
	"A master\'s skill in liquid form": "液态化的技能点数",
	"Amplifies even significantly muffled sounds.": "即使细碎的低语也能放大。",
	"Converts passive information into short-term benefit": "让被动获取的资源派上大用场，厚积薄发！",	
	"Purchase Cost": "解锁花费",
	"Raw mana injected right into the veins of a mage can allow for sustained casting, if one disregards the side-effects": "也许把未经提炼的法力注入静脉能提高法力速率，这可能会有点痒	（译者注：不要往自己静脉打奇怪的东西啊！）",
	"Temporarily grants you an impeccable ability to acquire valuables.": "获得一段时间的研究经费支持，包括宝石碎片",
	"This reddish potion causes a surge of energy in the imbiber, at the expense of health": "这种略带红色的药剂会让身体超载",
    "Removes most forms of inisidious motion impairment.": "治疗大多数行动不便的症状",
	"Cures most common ailments and fortifies the body.": "治疗大多数常见的小毛病并增强体质",
    "Unusually, prepared by baking special herbs into a brownie.": "这些草药居然能用来做巧克力蛋糕",
	
	//异常效果：
	"sick": "疾病",
	"fear": "恐惧",
	"enrage": "狂化",
	"charmed": "魅惑",
	"quake": "失衡",
	"quell": "压制",
	"sacked": "束缚",
	
	
	//简单的词语：
	
	"When used": "效果",
	"potion": "药剂",
	"action cure: paralysis,enrage,charmed,fear,silence,sick": "抵抗效果：麻痹，狂化，魅惑，恐惧，沉默，疾病",
	"action targets: self": "指定目标：自己",
	"Targets: all": "指定目标：全部",
	"Targets: allies": "指定目标：盟友",
	"Targets: enemies": "指定目标：敌方",
	"Applies": "效果",
	"Attack": "攻击",
	"Attack hit": "攻击命中",
	"tohit": "命中率",
	" tohit": "命中率",
	"Damage": "伤害",
	"Duration": "持续时间",
	"Effects": "影响",
	"Results": "结果",
	"Kind": "种类",
	"air": "风属性",
	"chaos": "混沌（虚空）属性",
	"earth": "地属性",
	"fire": "火属性",
	"light": "光属性",
	"mana": "奥术属性",
	"nature": "自然属性",
	"shadow": "暗影属性",
	"spirit": "精神属性",
	"water": "水属性",

    //部分装备名称：
	
	"loop": "臂带",
	"band": "手环",
	" hide jerkin": "皮坎肩",
	" hide hat": "皮帽",
	" hide band": "皮指环",
	" hide loop": "皮指绳结",
	" hide girdle": "皮腰带",
	" hide gloves": "皮手套",
	" hide helm": "皮头盔",
	" hide greaves": "皮胫甲",
	" hide padded armor": "皮厚甲",
	" hide 护身符": "皮护身符",
	" hide 戒指": "皮戒指",
	
	"adamantine 护身符": "合金护身符",
	"adamantine 戒指": "合金戒指",
	"adamantine axe": "合金斧子",
	"adamantine band": "合金指环",
	"adamantine battleaxe": "合金战斧",
	"adamantine boots": "合金靴子",
	"adamantine cane": "合金手杖",
	"adamantine cap": "合金帽子",
	"adamantine chainmail": "合金锁甲",
	"adamantine cincture": "合金腰甲",
	"adamantine club": "合金短棒",
	"adamantine collar": "合金衣领",
	"adamantine conical helm": "合金项圈",
	"adamantine girdle": "合金腰带",
	"adamantine greatstaff": "合金法杖",
	"adamantine greaves": "合金胫甲",
	"adamantine hat": "合金帽子",
	"adamantine helm": "合金头盔",
	"adamantine knife": "合金小刀",
	"adamantine longsword": "合金长剑",
	"adamantine loop": "合金指绳结",
	"adamantine mace": "合金狼牙棒",
	"adamantine necklace": "合金项链",
	"adamantine pendant": "合金吊坠",
	"adamantine plate mail": "合金板甲",
	"adamantine rod": "合金魔杖",
	"adamantine spear": "合金长矛",
	"adamantine staff": "合金棍子",
	"adamantine sword": "合金剑",
	"adamantine wand": "合金魔棒",
	"adamantine warhammer": "合金战锤",
	"adamantine wings": "合金翼甲",
	
	
	//怪物名（准备中）
	"basilisk": "蛇怪",
	
	
	//资源group
	"books": "典籍",
	"runes": "符石",
	"necromancy": "死灵术",
	"gems": "宝石",
	"puppets": "木偶",
	"other": "其它",
	"Actions": "行动",
	"Tasks": "任务",
	"Upgrades": "升级",

	"stamina": "耐力",
	"Stamina": "耐力",
	"life": "生命",
	"Life": "生命",
	"Name": "名字",
	"Title": "头衔",
	"Notoriety": "名望",
	"Level": "等级",
	"Experience": "经验",
	"Virtue : Evil": "善良：邪恶",
	"Skill Points": "技能点",
	"Rest": "休息",
	"Mount": "坐骑",
	"mount": "坐骑",
	"Distance": "距离",
	"Classes": "阶级",
	"Progress Cost": "进度成本",
	"Results": "结果",
	"Cost": "成本",
	"Effects": "效果",
	"Focus": "专注",
	"Save": "保存",
	"Load": "读取",
	"Get Save": "下载存档",
	"Hall Save": "下载殿堂存档",
	"[Load Save]": "[加载存档]",
	"Wipe Wizard": "删除角色",
	"Wipe Hall Save": "删除殿堂存档",
	"Wizard's Hall": "巫师殿堂",
	"Find": "查找",
	"Hide Maxed": "隐藏已满",
	'\n			Train': '训练',
	'\n			Stop': '停止',
	'Space': '空间',
	'Furnishing': '家具',
	'Owned': '已拥有',
	'Maxed': '达上限',
	'Unowned': '未拥有',
	'Blocked': '已锁定',
	'Home': '家园',
	'Werry': '位面',
	'Sort Level': '按等级排序',
	'Complete': '已完成',
	'Dungeon': '地下城',
	'Explore': '探索',
	'Enter': '进入',
	'Retreat': '撤退',
	'Luck': '幸运值',
	"defense": '护甲',
	'Defense': '防御',
	'Dodge': '闪避',
	'Damage Bonus': '伤害加成',
	'Bonus Damage': '加成伤害',
	'Hit Bonus': '命中加成',
	'Speed': '速度',
	'Weapon': '武器',
	'Resists': '抵抗',
	'Immunities': '免疫',
	'fire': '火',
	'water': '水',
	'air': '风',
	'earth': '地',
	'light': '光',
	'shadow': '暗影',
	'arcane': '奥术',
	'physical': '物理',
	'natural': '自然',
	'poison': '毒素',
	'disease': '疾病',
	'Stop All': '全部停止',
	'Clear': '清除',
	'event': '事件',
	'unlock': '解锁',
	'loot': '拾取',
	'combat': '战斗',
	'Modifications': '修订',
	'Learn': '学习',
	'Cast': '施放',
	'Memorize': '记忆',
	'Memorized': '已记忆',
	'Remove': '移除',
	'No space remaining. Sell items or find a new Home.\n			': '没有剩余空间。 出售物品或找到新家。',
	'If your max gold is not enough to buy a new home, free space for more chests.': '如果你达到金币上限都买不起新家，腾出点地方买更多的箱子吧。',
	'\n		Roll-over Item and hold {Shift} + {Number} to assign quickslot.': '滚动物品并按住{Shift} + {数字}可以分配快速插槽。',
	'\n		Press {Number} again to use quickslot Item.\n	': '再次按{数字}以使用快速插槽物品。',
	"Enchantment levels on an Item cannot exceed Item's enchant slots.": '物品的附魔等级不能超过物品的附魔槽。',
	'animation': '机械',
	'nature': '自然',
	'spirit': '精神',
	"mana": "法力",
	'charms': '魅惑',
	'astral': '星空',
	'Craft': '制造',
	'right': '右',
	'left': '左',
	'ring': '戒指',
	'fingers': '手指',
	'neck': '颈部',
	'shins': '腿',
	'waist': '腰',
	'hands': '手',
	'head': '头',
	'back': '背部',
	'feet': '脚',
	'chest': '胸',
	'trinket': '饰品',
	'Brew': '调制',
	'Resume': '恢复',
	'Enchant': '附魔',
	'Need': '需求',
	'Purchase Cost': '采购成本',
	'max activity': '行动上限',
	"max magicgems": "魔法宝石上限",
	"max prismatic": "棱柱上限",
	"prismatic rate": "棱柱速率",
	"max prismaticgems": "棱柱宝石上限",
	"max elementalgems": "元素宝石上限",
	"max element": "元素上限",
	"max elemental": "元素上限",
	"elemental 经验值": "元素知识 经验值",
	"activity 经验值": "行动 经验值",
	"elemental rate": "元素知识速率",
	"max primordialgems": "原始宝石上限",
	"max primordial": "原始上限",
	"max elementalrunes": "元素符文上限",
	"max primaticrunes": "棱柱符文上限",
	"max primordialrunes": "原始符文上限",
	"max manas": "法力能量上限",
	"manas rate": "法力能量速率",
	"max t_runes": "符石上限",
	"max spelllist": "法术列表上限",
	"max inventory": "库存上限",
	"max candle": "蜡烛上限",
	"max stress": "压力上限",
	"stress rate": "压力速率",
	"Max": "上限",
	"Buy": "购买",
	"Sell": "出售",
	"home": "家园",
	'Flee': '逃跑',
	'None': '无',
	'Cancel': '取消',
	'Confirm': '确认',
	'Skip Warning': '跳过警告',
	'Locks': '锁定',
	'LOOT': '掠夺',
	'RETREAT': '撤退',
	'Alternate Wizard classes of this tier will be locked.': '这一层的其它巫师职业将被锁定。',
	'This action is not reversible. Continue?': '这个动作不可逆，是否确定？（译者注：一般都有一些负面效果，请先导出存档。）',
    "(Full)": "(完整)",
    "Auto-Save": "自动保存",
    "Close": "关闭",
    "clean stables": "清理马厩",
    "Clean Stables": "清理马厩",
    "Combat": "战斗",
    "LOADING DATA...": "加载数据中...",
    "player": "玩家",
    "main": "首页",
    "Idle": "空闲",
    "gold": "金币",
    "basic": "基础",
    "Actions will only be performed if their outputs can be fully collected": "仅当收益可全额收取时，才会执行对应行动",
    "barrier": "屏障",
    "Body": "身躯属性",
    "Compact Mode": "紧凑模式",
    "Dark Mode": "深色模式",
    "Display total task effects": "显示全部任务效果",
    "Effects:": "效果：",
    "Elemental": "元素系",
    "Event": "活动事件",
    "Expand Resource Rate": "展开资源倍率",
    "extra stats": "额外属性",
    "Fast-forward": "快进加速",
    "Fastforward speed": "快进速度",
    "Fundamental Energies": "本源能量",
    "Gameplay adjustments": "玩法调整",
    "It's stable employment.": "稳定挂机收益",
    "Loot": "战利品",
    "Maximized efficiency mode": "极致效率模式",
    "Periodically save game to storage. Game is saved to Browser storage by default.": "定期将游戏存档至本地存储，默认存档至浏览器缓存",
    "pouch": "小袋子",
    "Press {Number} again to use quickslot Item.": "再次按下对应数字键，即可使用快捷栏物品",
    "Primal": "原始本源",
    "Prismatic Energies": "七彩元能",
    "Reddit": "Reddit社区",
    "relax": "休息",
    "Relax": "休息",
    "Resting": "休息中",
    "Results:": "结果：",
    "Roll-over Item and hold {Shift} + {Number} to assign quickslot.": "鼠标悬停物品并按住Shift+数字键，可设置快捷栏",
    "Shows remaining costs to pay and resources to acquire until next completion (for tasks with completion time of more than 1 second)": "显示距任务完成还需消耗的资源与剩余时长（适用于耗时超1秒的任务）",
    "Smooth bars": "平滑进度条",
    "Specialties & Menaces": "专长与负面特质",
    "Speedup factor for fast-forward feature. It is not recommended to set it above 25, depending on your PC performance.": "快进功能倍率，建议不要超过25，具体视电脑性能而定",
    "Starting Out": "新手起步",
    "Storage": "仓库存储",
    "stored time": "已缓存时长",
    "Test Site": "测试服",
    "Tooltip Stats": "悬浮提示属性",
    "Used to hide and unhide entries. This setting is retained between characters.": "用于隐藏/显示条目，设置对所有角色永久生效",
    "vigor": "活力",
    "Warning! This can prevent you from fully filling your resources to max, but will prevent wastefully underpoducing.": "警告！该设置可能导致资源无法堆满上限，但可避免产量不足造成浪费",
    "Wizard life-force.": "法师生命之力",
    "Working from home.": "在家里工作。",
    "Endurance": "耐力",
    "Gold": "金币",
    "Gold coins.": "金币。",
    "Keep your money safe.": "保管你的财富资产。",
    "Modifications:": "属性改动：",
    "Pouch": "小袋子",
    "Seems a tad pricey for a bag.": "这个背包定价略显偏高。",
    "Stored Time": "离线存储时长",
    "Time since you last checked in. Can be used to speed up the game.": "距上次登录的离线时长，可用于加速游戏进度。",
    "Used to mark and unmark entries as favourites. This setting is retained between characters.": "用于将条目设为/取消收藏，设置全角色通用保留。",
    "Vigor": "活力",
    "Where does time go when you aren't looking?": "离线期间时间仍在悄然流逝。",
    "Your capacity for short-term exertions.": "短时间爆发负重与行动耐力上限。",
    "Displays your active and waiting tasks in greater detail.": "更详细地展示当前进行中与待执行任务。",
    "Show calculated resource income from modified rate R, converters C, running tasks T, and buffs B.": "显示由修正倍率R、转化器C、运行任务T及增益buff B共同计算得出的资源收益。",
    "relaxing": "休息中",
    "A novice can get by with very basic scrolls, hopefully you won't need any of the pricier ones.": "新手只用基础卷轴就能过渡，希望你无需用到高价卷轴。",
    "buy scroll": "购买卷轴",
    "Buy Scroll": "购买卷轴",
    "Materials": "材料",
    "A tattered scroll": "一个破旧卷轴",
    "Apprenticeship": "学徒之路",
    "Class Unlocked: Apprenticeship": "职业已解锁：学徒之路",
    "knowledge": "知识",
    "research": "研究",
    "Research": "研究",
    "Research into the Arcane.": "奥术学识研究",
    "Research Rate: 0.005": "研究速率：0.005",
    "Scroll of arcane lore.": "奥术学识卷轴",
    "scrolls": "卷轴",
    "Scrolls": "卷轴",
    "Study": "学习",
    "study": "学习",
    "You buy a strange scroll from a travelling peddler. If you could only decipher the cryptic symbols.": "你从流浪商人手中买下一卷神秘卷轴，唯独无法解读上面晦涩的符文。",
    "Study arcane scrolls.": "学习奥术卷轴。",
    "Use stored time to speed up the game": "利用储存的时间来加快游戏进程。",
    "studying scrolls": "学习卷轴",
    "🛠️Evil\n🛠️Virtue\n🛠️Neutrality": "🛠️邪恶\n🛠️善良\n🛠️中立",
    "3x Glossary Entries on Mechanics Unlocked": "3条游戏机制术语词条已解锁",
    "After paying a small fee, you became apprenticed to a local wizard.": "缴纳少量费用后，你拜入当地一位法师门下成为学徒",
    "Apprentice": "学徒",
    "Become an apprentice.": "成为学徒",
    "Class": "职业",
    "Common way to carry coins.": "存放金币的常用容器",
    "Disables:": "已禁用：",
    "do chores": "做家务",
    "Do Chores": "做家务",
    "Equipment": "装备",
    "glossary": "术语图鉴",
    "alcove": "僻静小屋",
    "purse": "钱包",
    "Purse": "钱包",
    "run errands": "跑腿",
    "Run Errands": "跑腿",
    "mage lore": "法师学识",
    "skills": "技能",
    "Standard apprentice work.": "学徒的日常本职工作",
    "Upgrade Unlocked: purse": "升级项目已解锁：钱袋",
    "ichor": "灵液",
    "🔥hawthorn blossom": "🔥山楂花",
    "Abyssal Depths: First Layer": "深渊之境：第一层",
    "adventure": "冒险",
    "air gem": "风之宝石",
    "Arag Heights": "阿拉格高地",
    "Arag Wastes": "阿拉格荒原",
    "arcana": "奥术秘能",
    "arcane gem": "奥术宝石",
    "Auto Focus": "自动专注",
    "Barren mountains on the coast of Arazor.": "阿拉佐尔海岸的荒芜群山",
    "Basilisk Hide": "蜥怪外皮",
    "Below Mt. Gorborung": "戈尔博隆山脚下",
    "beltane 🔥": "🔥贝尔坦节",
    "bestiary": "怪物图鉴",
    "blood gem": "鲜血宝石",
    "bodies": "躯体",
    "bone dust": "骨粉",
    "bones": "骨头",
    "Charred Keep": "焦黑要塞",
    "Clash": "交锋对决",
    "codices": "手稿",
    "Companion:": "同伴：",
    "Complete to discover": "完成即可解锁发现",
    "constructs": "构装造物",
    "Corivar's Castle Courtyard": "科里瓦尔城堡庭院",
    "Desilla was known as much for her entertainments as her ruthlessness.": "德茜拉既以纵情享乐闻名，也以冷酷无情著称。",
    "Desilla's Grotto": "德茜拉洞窟",
    "dreams": "幻梦",
    "earth gem": "大地宝石",
    "earth runes": "大地符文",
    "Elemental Rift": "元素裂隙",
    "Eryl Eyot": "艾瑞尔小岛",
    "esoteric": "玄奥秘术",
    "Explore Treffil Wood": "探索特雷菲尔林地",
    "Fazbit's Workshop": "法兹比特工坊",
    "fire gem": "烈焰宝石",
    "fire runes": "烈焰符文",
    "Fire-cursed Shack": "烈焰诅咒囚屋",
    "fly": "飞行",
    "Fly": "飞行",
    "Fly on the winds.": "乘风翱翔",
    "gemstones": "宝石晶矿",
    "Genezereth": "吉尼泽瑞斯",
    "Goblin Camp": "哥布林营地",
    "Hall Of Ages": "岁月殿堂",
    "Haunted Manor": "闹鬼庄园",
    "herbs": "草药",
    "In all the world, the most enjoyable place to die.": "世间最令人安然的归宿之地",
    "light gem": "光明宝石",
    "Lillit's Spring": "莉莉特之泉",
    "Locale": "地域",
    "Loot:": "战利品：",
    "machinae": "机械造物",
    "materials": "材料",
    "Max Charms: 0.5 per 1 amount (rounded down) up to 2 (resulting in 1)": "符咒上限：每1份资源提升0.5点（向下取整），上限2点（最终为1）",
    "May Meadow": "五月草原",
    "Mount Gorborung": "戈尔博隆山",
    "Mount:": "坐骑：",
    "nature gem": "自然宝石",
    "Ogre Cavern": "食人魔洞穴",
    "On First Completion:": "首次完成奖励：",
    "Orc Camp": "兽人营地",
    "Peregrination": "四方游历",
    "Pidwig's Cove": "皮德维格海湾",
    "potion base": "药剂基底",
    "potions": "药剂",
    "Rithel": "里塞尔",
    "Ruined Crypt": "破败墓穴",
    "Rumors say that deep in the woods, there is a shack once inhabited by a wizard obsessed with fire. He has not been seen for years and terrible heat can be felt emanating from the place": "传闻密林深处有一间小屋，曾住着一位痴迷烈焰的法师。他已多年不见踪影，屋内却始终散发出骇人的热浪",
    "rune stones": "符文石",
    "Sands Of Orrem": "奥瑞姆沙海",
    "Seredite Temple": "塞瑞德神庙",
    "shadow gem": "暗影宝石",
    "Site Of Learning, Dungeon": "学识之地 · 地牢",
    "Skittering Caverns": "蠕行洞穴",
    "sleeping": "沉睡",
    "souls": "灵魂",
    "spellcraft": "法术造诣",
    "spells": "法术",
    "spirit gem": "圣灵宝石",
    "star shard": "星陨碎片",
    "Stony Hills": "石丘旷野",
    "tempus": "时序之力",
    "The Catacrypts": "地下古墓群",
    "The Great Bog": "大沼泽",
    "The Lost Menagerie": "失落异兽园",
    "The Unstable Spire": "不稳尖塔",
    "They say the roots of the mountain extend deeper than its heights.": "传言此山根基深埋地底，远比山体巍峨更高深",
    "Lightless": "无光者",
    "tomes": "典籍",
    "Training Grounds": "训练场",
    "Treffil Woods Edges": "特雷菲尔林地边缘",
    "Under Den": "巢穴下层",
    "Veldran's Storehouse": "威尔德伦仓库",
    "Veldran's Wreck": "威尔德伦残骸",
    "Village Fields": "村庄田野",
    "void": "虚空",
    "water gem": "流水宝石",
    "A hefty tome of knowledge.": "厚重的学识典籍",
    "Allies": "友方单位",
    "Arcana": "奥术秘能",
    "By Greater Light Spear": "施展圣光巨矛",
    "By Quake": "施展大地震击",
    "Codex of arcane lore.": "奥术学识典籍",
    "Codices": "手稿",
    "cotton": "棉花",
    "Earth Runes": "大地符文",
    "Enemies": "敌人",
    "Fire Runes": "烈焰符文",
    "Hawk": "雄鹰",
    "Hawk Slain": "击杀雄鹰",
    "iron": "铁矿",
    "Iron": "精铁",
    "Profound mystical knowledge.": "深邃的神秘学识",
    "resist silence": "沉默抗性",
    "Rune etched with lines of fire.": "刻有烈焰纹路的符文",
    "Rune ingrained with moonstone.": "嵌有月石纹理的符文",
    "Rune Stones": "符文石",
    "Runes": "符文",
    "Runes carved on pieces of stone.": "镌刻在石块上的符文",
    "Runes, Elemental Runes, Prismatic Runes": "普通符文、元素符文、虹彩符文",
    "Scrapling": "残孽小怪",
    "Scrapling Slain": "击杀残孽小怪",
    "splendor": "光辉华彩",
    "Tomes": "典籍",
    "Use": "使用",
    "Wizrobe": "巫师",
    "Wizrobe Casts ⭐Phrenesis' Healing Circle": "巫师 施放⭐狂愈疗愈之环",
    "Wizrobe Casts Greater Light Spear": "巫师 施放圣光巨矛",
    "Wizrobe Casts Quake": "巫师 施放大地震击",
    "Wizrobe Dodges Scratch": "巫师 闪避利爪攻击",
    "Wolf": "野狼",
    "A conduit for magic energy.": "魔法能量的传导媒介。",
    "A measure of reputation. Each point of notoriety provides one point of hall prestige. Hall prestige may be spent to purchase Hall Upgrades.": "声望的量化数值。每1点恶名可提供1点厅堂声望。厅堂声望可用于购买厅堂升级项目。",
    "A new wing of the Great Hall where Wizards can lodge in comfort.": "大厅新建配楼，可供法师舒适栖居。",
    "Air": "风元素",
    "An ancient artifact from before the art of Oneiromancy was lost. Makes users capable of controlling dreams... and vice-versa.": "一件源自解梦术失传前的古老神器，能让使用者掌控梦境……亦会被梦境反噬。",
    "An expansive chamber for viewing the heavens.": "用于观星望远的宏阔殿堂。",
    "Blunt": "钝击",
    "Bodily Configuration": "躯体构型",
    "Body shape": "身形体态",
    "Bodyplan": "躯体模板",
    "Classrooms": "研习教室",
    "Click to enable searching": "点击开启搜索功能",
    "Companion": "伙伴",
    "Dedicated classrooms for efficient study and transfer of knowledge.": "专属研习教室，用于高效研学与知识传承。",
    "Dedicated stabling for the hall's mounts. Useful for discerning those with aptitude for magic.": "为厅堂坐骑专属打造的厩舍，便于甄别拥有魔法天赋之人。",
    "Defense:": "防御：",
    "Determines your accuracy. Every 100 hit bonus halves opponents effective dodge": "决定你的命中精度。每100点命中加成，可将敌方有效闪避率减半。",
    "Determines your chance to dodge.": "决定自身闪避概率。",
    "Dodge:": "闪避：",
    "Dream Chamber": "梦境密室",
    "Earth": "地元素",
    "Enhanced Laboratories": "进阶实验室",
    "Evil": "邪恶",
    "Fire": "火元素",
    "Global Potencies": "全域威能",
    "Great Wing": "宏阔配楼",
    "Hall Upgrades": "厅堂升级",
    "Hit Bonus:": "命中加成：",
    "humanoid": "人型",
    "Humanoid": "人型生物",
    "In some time and place, even dreams were once real.": "在某时某地，梦境也曾真实存在。",
    "Increases your overall chance to gain loot.": "提升整体战利品获取概率。",
    "Leisure": "闲适值",
    "Light": "光元素",
    "Luck:": "幸运：",
    "Magic Stables": "魔法厩舍",
    "Mana": "魔力",
    "Mechanical assistants and automated delivery systems.": "机械助手与自动配送装置。",
    "Nature": "自然元素",
    "Notoriety:": "恶名：",
    "Oneiromancy": "解梦术",
    "Personal": "个人属性",
    "Pierce": "穿刺",
    "Potencies": "威能属性",
    "Reduces damage taken.": "减免受到的伤害。",
    "Shadow": "暗影元素",
    "Slash": "劈砍",
    "Speed:": "速度：",
    "Spellspire": "法能尖塔",
    "Spirit": "圣灵元素",
    "Stables": "厩舍",
    "Star Chamber": "星曜殿堂",
    "Status Negation": "状态豁免",
    "Survey says, only ring fingers matter": "坊间戏称：唯有无名指至关重要",
    "Waif": "流浪孤童",
    "Titles": "称号",
    "Two hands, two legs, hopefully a head": "双手双腿，最好还长着头",
    "Virtue": "善良",
    "Waif": "流浪孤童",
    "Water": "水元素",
    "Languages": "语言",
    "scribe scroll": "抄录卷轴",
    "sell gem": "出售宝石",
    "sell scroll": "出售卷轴",
    "Sell Herbs": "出售草药",
    "Grand Quest": "大任务",
    "imbue gem": "灌注宝石",
    "Magic": "魔法",
    "craft rune": "制作符文",
    "craft bag of demons": "制作恶魔之袋",
    "craft timepiece": "制作计时器",
    "craft gem": "制作宝石",
    "Crafting": "制作",
    "crafting table": "制作台",
    "🔥gather hawthorn blossoms": "🔥采摘山楂花",
    "A complex alchemical process drips arcane energy onto gemstones.": "一套繁复的炼金工序，将奥术能量缓缓灌注于宝石之上。",
    "A good archive does your research for you.": "完善的典籍文库，能为你的研究代劳解惑。",
    "A grand hall to entertain guests and supplicants.": "一座宏伟厅堂，用以招待宾客与求道者。",
    "A sanctuary for orphans and paupers.": "孤儿与贫民的庇护之所。",
    "a scrupulous path": "谨守正道",
    "A storeroom of arms.": "兵器库房",
    "A vast and practical fortress, for the magic user with enemies. Or targets.": "一座宏大实用的要塞，专为树敌众多、亦或是目标遍地的施法者所设。",
    "A Vile Path": "邪秽歧途",
    "Advancement": "进阶修为",
    "advise notables": "向名流建言献策",
    "Advise Notables": "向名流建言献策",
    "Aerated Abode": "浮空居所",
    "Aeromancy": "御风术",
    "Affluence": "富足之资",
    "Aided Thoughts": "灵思助益",
    "Alchemy": "炼金术",
    "Alembic, Furniture": "蒸馏器皿 · 家具",
    "Alignment Bias": "阵营倾向",
    "Animals": "野兽生灵",
    "Animate Skeletal Runecarver": "活化骸骨符文匠",
    "apprentice": "学徒",
    "Aquamancy": "控水术",
    "arcane alembic": "奥术蒸馏器",
    "Arcane Alembic": "奥术蒸馏器",
    "arcane archive": "奥术文库",
    "Arcane Archive": "奥术文库",
    "arcane bestiary": "奥术异兽图鉴",
    "Arcane Expertise": "奥术专精",
    "arcane orb": "奥术法球",
    "arcane thievery": "奥术窃术",
    "Arcane Thievery": "奥术窃术",
    "Arcane Veil": "奥术帷幕",
    "armory": "军械库",
    "Armory": "军械库",
    "Armssource, Furniture": "兵器陈列台 · 家具",
    "aryabhatiya": "阿耶波多经卷",
    "Ashen Glory": "烬灭荣光",
    "assemble machina": "组装机械造物",
    "assemble puppet": "组装傀儡人偶",
    "Astral Ward": "星界护罩",
    "Astronomy": "星象天文",
    "attune to depths": "与深渊共鸣",
    "attune to wilderness": "与荒野共鸣",
    "auto-vivisection": "自体解剖",
    "automated miner": "自动采矿机",
    "backyard": "后院",
    "bag of holding": "储物纳物袋",
    "banquet hall": "盛宴厅堂",
    "Banquet Hall": "盛宴厅堂",
    "Bargain": "议价之道",
    "basic tools": "基础工具",
    "Beltane 🔥": "🔥贝尔坦节",
    "Bibliophile": "藏书癖者",
    "bind codex": "绑定古籍",
    "binding circle": "封印法阵",
    "blood gem cache": "鲜血宝石储藏库",
    "blood siphon": "鲜血汲取",
    "bloodbane's anvil": "灭血铁砧",
    "Bloodbane's Anvil": "灭血铁砧",
    "bloodbane's forging": "灭血锻铸",
    "bolthole": "避难密室",
    "bonfire": "营火",
    "book carousel": "典籍旋转架",
    "Book Furniture, Furniture": "典籍家具·陈设",
    "bookcase": "书柜",
    "bookshelf": "书架",
    "botanical kit": "植物研究套件",
    "botanical study": "植物学识研究",
    "bottomless pit": "无底深渊",
    "brass candelabra": "黄铜烛台",
    "breathing exercises": "吐纳调息术",
    "Bubbling Concoctions": "冒泡炼金合剂",
    "burning coals": "燃烬炭火",
    "cairn": "石冢陵标",
    "Calligraphy Set": "文房墨宝套组",
    "campfire": "篝火",
    "Casement Window": "竖格落地窗",
    "caskets": "灵柩宝匣",
    "castle": "城堡",
    "Castle": "城堡",
    "castle restoration": "城堡修缮",
    "catasterismi": "星宿星图录",
    "cavernous stillness": "洞穴死寂",
    "chant": "咏唱咒文",
    "Chronos Shell": "时序圣壳",
    "cipher journal": "密码手记",
    "cleansing fire": "净化圣火",
    "clepsydra": "水漏计时器",
    "clockwork cabinet": "发条柜",
    "closed-loop runic workspace": "闭环符文工坊",
    "cloud chamber": "云境密室",
    "coagulate gem": "凝萃宝石",
    "codex loom": "典籍织机",
    "Collect hawthorn blossoms at dawn on Beltane morning, when their magic is strongest. The fae watch but allow those who show proper respect.": "于贝尔坦节清晨拂晓采摘山楂花，此时其魔力最为鼎盛。仙灵默默注视，却会善待心怀敬意之人。",
    "Compile Tome": "编撰典籍",
    "compile travelogue": "编撰游历手记",
    "Conversion per Arcane Alembic": "单次奥术蒸馏器转化率",
    "converters": "转化器具",
    "corporis fabrica": "躯体构塑术",
    "cot": "小床",
    "Arms of Iron": "钢铁武备",
    "Craftwork": "精工造物",
    "create still room": "搭建静思密室",
    "creeping vine": "匍匐藤蔓",
    "critter dissections": "生灵解剖",
    "Cure customers of magical ailments.": "为顾客治愈各类魔法顽疾。",
    "Cursed Slab": "诅咒石板",
    "dark shrine": "暗黑神龛",
    "demonic examinations": "邪魔解析",
    "demonic pentagram": "恶魔五芒阵",
    "Demonology": "恶魔学",
    "Den of Pleasure": "欢愉之巢",
    "Dimensional Well": "次元之井",
    "Disaster's Emissaries": "灾厄使者",
    "dissect cadaver": "解剖尸骸",
    "Divination": "占卜术",
    "diving": "潜水寻踪",
    "dreamweaver": "织梦师",
    "Dunes of Orrem": "奥瑞姆沙丘",
    "dungeon": "地牢",
    "dwarven runecrafter": "矮人符文工匠",
    "earth werry": "地行灵舟",
    "Echo of the Ages": "岁月回响",
    "Education": "学识教化",
    "elemental flux": "元素通量",
    "elemental siphon": "元素汲取",
    "Ember Surge": "余烬奔涌",
    "enchanted fountain pen": "附魔钢笔",
    "Enchanted Scrollery": "附魔卷轴馆",
    "Enchanted Study": "附魔研习室",
    "enchanting table": "附魔台",
    "Endless Stamina": "无尽耐力",
    "Energy Spectrum": "能量谱系",
    "Equestrian": "骑术造诣",
    "Erudition": "博学通识",
    "Esoteric Occultist": "玄秘术士",
    "Eternal Transcendence": "永恒超脱",
    "Event Horizon": "事件视界",
    "Evil Acts": "恶行罪孽",
    "expanded interests": "拓展志趣",
    "Exploration": "探索游历",
    "extra candles": "备用蜡烛",
    "Fazbit's Magnum Opus": "法兹比特旷世杰作",
    "Fire mana.": "火焰魔力。",
    "fire werry": "火行灵舟",
    "firegazing": "观火冥思",
    "fireplace": "壁炉",
    "focus": "凝神专注",
    "Fool's Gold": "愚人金",
    "Forsaking war and violence, Bloodbane devoted himself to crafting new forms of magic.": "弃战乱杀伐于不顾，血厄尊者潜心开创全新魔法体系。",
    "found collective": "建立聚落",
    "fountain": "喷泉",
    "fourposter": "四柱大床",
    "From worried village councils to bumbling barons, they all require your advice.": "从忧心忡忡的村议会到笨拙庸碌的贵族男爵，皆需你出谋划策。",
    "funerary rites": "丧葬祭仪",
    "Furniture": "家具陈设",
    "gargoyle": "石像鬼",
    "Gather Hawthorn Blossoms": "采摘山楂花",
    "gather herbs": "采集草药",
    "Gematria": "数字秘占术",
    "Geomancy": "地脉术",
    "Ghost Writer": "代笔灵影",
    "ghostly assistants": "幽冥助手",
    "glassware": "玻璃器皿",
    "gold portal": "黄金传送门",
    "Good Acts": "善行义举",
    "Gordian Knot": "难解死结",
    "Graduand Magus": "新晋法师",
    "Granite Barrier": "花岗岩壁垒",
    "graveyard": "墓园",
    "Great spells are often forged on iron.": "强大法术往往借精铁锻铸而成。",
    "Grimoire of Demons": "恶魔魔导书",
    "grind bones": "研磨骨粉",
    "grotesque": "畸怪造物",
    "grove trimming": "林地修整",
    "gryffon": "狮鹫",
    "heart Candle": "心焰圣烛",
    "herbal remedy": "草药疗方",
    "Herbalism": "草药学",
    "Hire Dwarven Runecrafter": "雇佣矮人符文工匠",
    "hold seance": "举行通灵降灵会",
    "Home Sweet Home": "温馨居所",
    "Home:": "居所：",
    "horse medicines": "马匹药剂",
    "Housing": "居住宅邸",
    "idle hobbies": "闲情雅趣",
    "Imbuement": "赋灵灌注",
    "Inner Peace": "内心澄静",
    "Input:": "投入：",
    "internalize lore": "融会学识奥义",
    "interrogate fiends": "拷问邪魔异类",
    "Interweaving": "交织秘术",
    "iron cell": "铁牢囚室",
    "iron chest": "铁质宝箱",
    "island management": "岛屿治理",
    "Knowledge": "学识智慧",
    "lake of fire": "烈焰之湖",
    "lattice fence": "格纹围栏",
    "lattice window": "花格窗棂",
    "leggery": "皮革制品",
    "lexyrinth": "典籍迷宫",
    "lexyrinth browsing": "典籍阅览",
    "library": "藏书馆",
    "Library Haul": "藏书馆收获",
    "light adaptation": "明光适应",
    "Loom": "织机",
    "lounge room": "休憩客厅",
    "Lumenology": "流明光学",
    "Lunar Calendar": "阴历历法",
    "luxury bedroom": "奢华卧室",
    "machina assembly": "机械组装",
    "machina workshop": "机械工坊",
    "Mage Lore": "法师学识",
    "Magic Beasts": "魔法异兽",
    "magic circle": "魔法法阵",
    "Magic Immemorial": "太古玄法",
    "mana adaptation": "魔力适应",
    "Mana Energies, Element, Prismatic": "虹彩元素魔力",
    "Mana Energies, Primal, Prismatic": "本源虹彩魔力",
    "Mana Proficiency": "魔力精通",
    "maniacal goals": "偏执执念目标",
    "map world": "世界地图",
    "Material Chest": "材料宝箱",
    "menagerie": "异兽园",
    "Mercantile Ventures": "商贸经营",
    "mineshaft": "矿井巷道",
    "model skeleton": "骨骼模型",
    "Morality Options": "道德取向",
    "Mountain Trekking": "山地跋涉",
    "murder": "杀戮恶行",
    "muscle studies": "肌肉学识研习",
    "Nathaniel insisted magic be used for the benefit of the unfortunate.": "纳撒尼尔主张魔法当造福贫苦众生。",
    "nathaniel's sanctuary": "纳撒尼尔庇护所",
    "Nathaniel's Sanctuary": "纳撒尼尔庇护所",
    "nature adaptation": "自然适应",
    "Nature mana.": "自然魔力。",
    "Nature Studies": "自然研习",
    "never-idle": "永不停歇",
    "new skies": "崭新天穹",
    "Night Owl": "夜枭行者",
    "nourish sprout": "滋养幼苗",
    "observe animals": "观察生灵",
    "observe magic beasts": "观测魔法异兽",
    "offer services": "提供服务",
    "ornate chest": "华丽宝箱",
    "Ornithology": "鸟类学",
    "orrery": "天体运转仪",
    "orthography": "正字文法",
    "Other": "其他",
    "Output:": "产出：",
    "pace": "步履节律",
    "palace restoration": "宫殿修缮",
    "Patron, Furniture": "赞助者雕像·陈设",
    "pedestal": "石台基座",
    "pegasus": "天马",
    "personal study": "私人研习室",
    "pet familiar": "灵宠伙伴",
    "phoenix quill": "凤凰羽笔",
    "picatrix": "皮卡特里秘术",
    "Pillage Graves": "盗掘古墓",
    "planar exploration": "位面探索",
    "planar vitality": "位面生机",
    "Plane": "位面",
    "Plane of Demons": "恶魔位面",
    "Plane of Spirits": "圣灵位面",
    "Planes Lore": "位面学识",
    "Pocket Dimension": "口袋次元",
    "pond": "池塘",
    "porta alchemica": "炼金之门",
    "Portal Network": "传送门网络",
    "potions room": "药剂室",
    "Potions": "药剂学",
    "Potted Milkweed": "盆栽马利筋",
    "powderize skull": "头骨研粉",
    "practice astrology": "修习占星术",
    "Predictive Padding": "预判护盾",
    "Preeminent Magus": "超凡大法师",
    "Prismatic Rift": "虹彩裂隙",
    "Progression Quests": "进阶任务",
    "puppet-making workshop": "傀儡工坊",
    "purchase gem": "购买宝石",
    "Pyromancy": "火焰法术",
    "Question elementals": "质询元素生灵",
    "question spirits": "通灵问灵",
    "Reactive Mending": "反应修复术",
    "read palms": "看相卜掌",
    "Realm Splitter": "界域割裂者",
    "record stars": "星象记录",
    "Refreshing Dew": "清润晨露",
    "reliquary": "圣物匣",
    "restore ruins": "遗迹修复",
    "Reviewing Your Notes": "研读手记笔记",
    "rite of vitality": "生机仪式",
    "Root Out Banditry": "清剿盗匪",
    "Ruins of Reverence": "圣尊遗迹",
    "rune chest": "符文宝箱",
    "rune construction": "符文构造",
    "Runic Dome": "符文穹顶",
    "Runic Labourers": "符文劳工",
    "runic printing press": "符文印刷机",
    "Rushlights": "微光油灯",
    "rusty cage": "锈蚀牢笼",
    "sand garden": "枯山水庭园",
    "sanguine apotheosis": "血色神化",
    "scriptorium": "缮写室",
    "scroll loom": "卷轴织机",
    "scroll rack": "卷轴架",
    "scry": "灵视占卜",
    "Scrying": "占卜观星",
    "sensory deprivation": "感官剥夺",
    "Sextant": "六分仪",
    "shadow adaptation": "暗影适应",
    "shopwork": "商铺劳作",
    "shrine": "神龛",
    "skeletal artifice": "骸骨造物术",
    "Skeletal Runecarver": "骸骨符文雕刻师",
    "sky exploration": "天穹探索",
    "skygazing": "观星冥想",
    "slumber": "沉睡入梦",
    "Slumber": "沉眠",
    "small chest": "小型宝箱",
    "Smith": "锻造匠人",
    "soil composition study": "土壤成分研究",
    "soundproof study": "隔音研习室",
    "Special": "特殊",
    "Spell Construction": "法术构创",
    "Spellcaster": "施法者",
    "Spellcraft": "法术技艺",
    "Spin Gold": "点石成金",
    "spin gold✅": "点石成金✅",
    "Spin straw into gold.": "点草成金。",
    "spinning wheel": "纺车",
    "spirit adaptation": "圣灵适应",
    "Spirit Communion": "通灵交感",
    "spirit examinations": "灵体解析",
    "stained glass dome": "彩绘玻璃穹顶",
    "star well": "星辰之井",
    "Stare Back": "凝眸回视",
    "starweb": "星网",
    "starwish": "星愿",
    "stone working kit": "石艺工具组",
    "stony resilience": "磐石韧体",
    "study star shard": "研习星碎残片",
    "study water cycle": "研习水文循环",
    "sublimate lore": "学识升华",
    "Sublimation": "奥义升华",
    "Summoning": "召唤术",
    "sustained imbuement": "持续赋灵",
    "sustained writing": "永续撰录",
    "Take on an apprentice to do work for you.": "收徒纳徒，令其为你打理杂务。",
    "Tattered Cobwebs": "残破蛛网",
    "taxidermy animals": "动物标本",
    "telescope": "天文望远镜",
    "temple expansion": "神殿扩建",
    "tend animals": "饲养灵兽",
    "Thaumaturgy": "奇术秘法",
    "The deepest sleep guards the greatest insights.": "最深的沉眠，守护着至高的洞见。",
    "The fae watch from the shadows, but allow respectful gathering.": "仙灵隐于暗影之中默默注视，亦会默许心怀敬意之人采摘灵物。",
    "Tier": "阶位",
    "time spiral": "时间螺旋",
    "Time Walk": "时光行步",
    "Timeline Bifurcation": "时间线分叉",
    "tome loom": "典籍织机",
    "tool of the trade": "本行器具",
    "tool practice": "器具修习",
    "Training Dummy": "训练假人",
    "Transformation": "蜕变转化",
    "trap soul": "禁锢灵魂",
    "trataka": "凝视冥修法",
    "Travel": "游历四方",
    "treasure room": "藏宝密室",
    "treat ailments": "医治顽疾",
    "Treat Ailments": "医治顽疾",
    "tree studies": "林木研习",
    "trial and error": "试错参悟",
    "Uncover The Crypt": "探秘陵窟",
    "unquenchable flames": "不灭焚焰",
    "unspin gold": "化金还原",
    "Use your powers to cajole, coerce, and cudgel gold from the pockets of civilians.": "运用自身能力哄诱、胁迫、强取平民钱财。",
    "vat": "炼金大缸",
    "vault": "地下宝库",
    "verdant alembic": "苍翠炼金蒸馏器",
    "Vesparia's Gilded Age": "维斯帕里亚黄金时代",
    "vile experiment": "邪秽实验",
    "vital alembic": "生机炼金蒸馏器",
    "vivarium": "生态饲育箱",
    "Vow of Neutrality": "中立誓约",
    "Walking backwards": "逆行缓步",
    "wander": "漫游",
    "Water Basin": "净水盆台",
    "weapon rack": "武器架",
    "Weavesource": "织法源具",
    "Well-Armed": "武备充盈",
    "Werry:": "灵舟：",
    "Whether they know it or not.": "无论他们自知与否。",
    "Why does it cost money?": "为何需要耗费资金？",
    "wildfire observation": "野火观测",
    "wind werry": "风行灵舟",
    "Wish Upon A Star": "向星许愿",
    "Wizard Association": "巫师协会",
    "wizard's hall": "法师厅堂",
    "wooden bed": "木床",
    "workshop": "工坊",
    "Workshop": "工坊",
    "World Lore": "世界学识",
    "writing desk": "书案书桌",
    "Zephyr Stride": "和风步韵",
    "ziggurat": "阶梯金字塔神庙",
    "A large spire which rose from the ground. It looks like it might collapse any day now.": "一座拔地而起的高耸尖塔，如今摇摇欲坠，仿佛随时都会倾颓。",
    "A scourge of towns and cities.": "城镇与城邦的灾厄祸根。",
    "A tear in the fabric of reality leads to a land of raw elements.": "现实肌理撕裂出一道裂隙，通往一片原始元素纵横之地。",
    "A vibrant meadow where hawthorn trees bloom and mayflowers carpet the ground. On Beltane, the old pacts loosen here first, and fae lights dance among the flowers.": "一片生机盎然的草甸，山楂树繁花盛放，五月花铺满地际。每逢贝尔坦节，古老契约最先在此松动，仙灵萤火在花间翩跹起舞。",
    "Abandoned, overgrown buildings. But security systems are still active in few of them.": "荒废蔓生的建筑群，其中少数区域的安防系统依旧保持运转。",
    "Also known as Barden's bog, no one can say exactly just who Barden was.": "此地亦被称作巴登沼泽，无人能确切道出巴登究竟是何人。",
    "An ancient crypt of crumbling stone.": "一座石体崩坏的古老陵窟。",
    "An ancient library at the bridge spanning Markhul's gap.": "横跨马尔库尔裂隙的石桥之上，矗立着一座古老藏书馆。",
    "An arid plain stretching across Arazor from the Arag Heights.": "一片干旱荒原，从阿拉格高地绵延至阿拉佐尔全境。",
    "At the bottom of the bottomless, lies an entrance to a plane darker than ink.": "无底深渊之底，藏着一处比墨色更为幽暗的位面入口。",
    "Beneath the tallest idrasil a great menagerie thrives beneath a second sky.": "至高世界树的荫蔽之下，一方异兽秘境在第二层天穹下繁衍生息。",
    "Burned black by its own denizens.": "被本土生灵焚作焦黑之地。",
    "Day and night the dark gates stand open to all... but to return to the open air... that is the task, that is the labor.": "黑暗之门日夜为众生敞开……但若想重返人间凡尘，便是重重考验，亦是无尽修行。",
    "Fae lights dance among the flowers, guiding those who honor the old ways.": "仙灵萤火花间流转，引守古道、心怀敬意之人前行。",
    "For hundreds of miles the great bog spreads across the dark center of Dhrune.": "广袤沼泽绵延数百里，横亘在德伦大陆晦暗的腹地。",
    "Hey Vizard, ghost here...": "喂，维泽德，我是灵体……",
    "Its creator and purpose are unknown to history. Perhaps all creatures exist within.": "它的创造者与建造初衷早已湮没于历史尘埃，或许万物生灵皆存于其内里之中。",
    "Its smouldering ruins once more begin to burn.": "余烬未熄的遗迹，再度燃起熊熊烈火。",
    "Lok'tar!": "为了荣耀！",
    "Must own a bottomless pit and meet distance requirements": "需拥有无底深渊，并满足距离条件。",
    "Off the stormy cliffs of Arazor a mass of cracked spars marks the resting place of the largest ship ever sailed by man.": "阿拉佐尔风浪滔天的断崖外，嶙峋断桅林立，标示着人类史上最大航船的葬身之地。",
    "Old Mirthemgnar dug its dungeons til they joined the hollows beneath the world. In terror they sealed them forever. Or so they tried.": "古老的米尔瑟姆纳部族深挖地牢，直至连通地底空洞。满怀恐惧的他们将其永久封印——至少他们曾试图如此。",
    "One of the most perilous mountains in the world. Many journey over its passes; none venture within.": "世间最凶险的山脉之一。无数人穿行其隘口，却无人敢深入腹地。",
    "Only a small trading post marks the boundary of the lost cities of Orrem. Weathered masonry jutting from the sands beyond bespeak monuments of unimaginable proportions.": "仅有一处小型贸易驿站，标示着奥雷姆失落古城的边界。风沙之外，风化石垣突兀林立，昭示着曾有难以想象的宏伟古迹屹立于此。",
    "Perform the Wander task 100 times.": "完成漫游任务100次。",
    "Proverbial den of thieves.": "名副其实的盗贼巢穴。",
    "Site Of Learning, Locale": "学识圣地 · 地域场景",
    "Some things are left to time.": "有些事物，只可交由时光沉淀。",
    "Tenwick's trail runs a circuit about the notable areas of Dhrune. On foot it takes the better part of a year to complete.": "滕威克小径环绕德伦大陆各处名胜蜿蜒曲折，徒步走完全程，几乎要耗费整整一年光阴。",
    "The deeper woods posses many features of interest to the magical scholar. The spirits of the place make sure to keep the troublemakers out.": "密林深处藏有诸多令法师学者心驰神往的奇景，此地的灵体自会将滋事之徒隔绝在外。",
    "The half-goblin Pidwig has sailed the waters around his bay for hundreds of years. In that time he has collected a myriad of interesting artifacts.": "半地精皮德维格，已在自家海湾航行了数百年之久。漫长岁月里，他收藏了数不胜数的奇珍古物。",
    "The knowledge within may be beyond price.": "其中蕴藏的学识，价值无可估量。",
    "The large grounds before the locked away estate once owned by Corivar.": "科里瓦尔昔日隐秘宅邸前，一片广阔空旷的庭园。",
    "The lost Hall of Ages was a gathering place of great and powerful patron mages.": "失落的岁月圣殿，曾是一众强大守护法师的聚首之地。",
    "The nearby village's fields are vast and full of opportunity for an aspiring mage.": "邻近村落的田野广袤无垠，对有志修行的法师而言，处处皆是机缘。",
    "The only treasures here, are those lost by adventurers searching for treasure.": "此地唯一的珍宝，皆是寻宝冒险者遗失的行囊遗物。",
    "The pesky creatures are everywhere.": "恼人的小怪生灵随处可见。",
    "The small and tranquil island is inhabited by an old hermit named Thyffr.": "这座宁静的小小岛屿，隐居着一位名为赛弗的隐士老者。",
    "These enchanted woods are not particularly dangerous.": "这片附魔林地并不算凶险莫测。",
    "Third of the Four Weirs of Dhrune.": "德伦四大堰坝之第三堰。",
    "This tiny outpost in the center of Thangmor outlasted even the pillars.": "桑摩尔腹地的这座小型前哨，存续岁月甚至胜过古老石柱。",
    "Tradition tells of a spring with enchanted waters. Investigations might prove revealing.": "传说此地有一处灵泉，泉水蕴有魔力，深入探寻或许会有惊人发现。",
    "Underwater, Dungeon": "水下 · 地牢场景",
    "Unsettling voices can be heard throughout the manor after dark": "夜幕降临后，庄园中四处可闻令人心神不安的低语声。",
    "Veldran never did manage to carve a kingdom from the wreck of Bodias' reign. But he did accrue a sizeable hoard.": "维尔德兰始终未能从波迪亚斯王朝的废墟中开辟出属于自己的王国，却积攒下了一笔数额庞大的宝藏珍藏。",
    "Who they were or why they built this ruined temple in the seaside cliffs is a mystery lost to time.": "究竟是何人、又为何在临海断崖建造这座破败神殿，早已沦为被时光遗忘的谜团。",
    "Would the ancient seredites appreciate the temple's new inhabitants?": "远古的赛瑞德族人，会接纳这座神殿的新住民吗？",
    "You could spend a century in Fazbit's lost workshop and not exhaust its creations.": "纵使在法兹比特的失落工坊流连百年，也无法穷尽其中的造物奇珍。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Po": "袋子",
    "Re": "休息",
    "CS": "清理",
    "Mythic": "神话",
    "Legendary": "传说",
    "Epic": "史诗",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Common": "普通",
    "SPD": "速度",
    "ATK": "攻击",
    "ARM": "护甲",
    "Lvl": "等级",
    "Unlock": "解锁",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "🦴": "🦴",
    "↑": "↑",
    "↑↓": "↑↓",
    "↓": "↓",
    "🌟": "🌟",
    "💀💀": "💀💀",
    "💀💀💀": "💀💀💀",
    "💀💀💀💀💀": "💀💀💀💀💀",
    "🔍": "🔍",
    "🔒": "🔒",
    "💀💀💀💀": "💀💀💀💀",
    "💀💀💀💀💀💀": "💀💀💀💀💀💀",
    "🦴🦴🦴": "🦴🦴🦴",
    "💀": "💀",
    "🔥": "🔥",
    "◄": "◄",
    "▶": "▶",
    "▼": "▼",
    "⚙": "⚙",
    "\xa0X\xa0": "X",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "Next at ": "下一个在 ",
    "Show Milestone Popups: ": "显示里程碑弹窗：",
    "Made by ": "作者 ",
	"🌳": "🌳",
	"📖": "📖",
	"🏰": "🏰",
	"⚔": "⚔",
    "⭐": "⭐",
    "❄️": "❄️",
    "\n			Next Improvement: ": "下一次提升：",
    "\n\n\t\texp: ": "经验：",
    "Space: ": "空间：",
    "mana: ": "法力：",
    "fire: ": "火：",
    "air: ": "风：",
    "water: ": "水：",
	'earth: ': '地：',
	'light: ': '光：',
	'shadow: ': '暗影：',
	'arcane: ': '奥术：',
	'physical: ': '物理：',
	'natural: ': '自然：',
	'poison: ': '毒素：',
	'disease: ': '疾病：',
	'Max Levels: ': '等级上限：',
	'Power: ': '能量：',
	'Slot: ': '插槽：',
	'upgrade Unlocked: ': '升级解锁：',
	'action Unlocked: ': '行动解锁：',
	'resource Unlocked: ': '资源解锁：',
	'class Unlocked: ': '职业解锁：',
	'Unlocked: ': '解锁：',
	'locale Unlocked: ': '地点解锁：',
	'furniture Unlocked: ': '家具解锁：',
	'skill Unlocked: ': '技能解锁：',
	'home Unlocked: ': '住房解锁：',
	'dungeon Unlocked: ': '地下城解锁：',
	'potion Unlocked: ': '药剂解锁：',
	'enchant Unlocked: ': '附魔解锁：',
	'spell Unlocked: ': '法术解锁：',
	'monster Unlocked: ': '怪物解锁：',
	'Title Earned: ': '获得头衔：',
	'title: ': '称号：',
	'max: ': '上限：',
    "Task Unlocked: ": "任务已解锁：",
    'Upgrade Unlocked: ':'升级已解锁：',
    "Resource Unlocked: ": "资源已解锁: ",
    "Skill Unlocked: ": "技能已解锁：",
    "Home Unlocked: ": "家园已解锁：",
    "Level: ": "等级: ",
    "Kind: ": "种类: ",
    "Crafting: ": "制作: ",
    "Title: ": "称号: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "❄️": "❄️",
    '🎃': '🎃',
	"🌳": "🌳",
	"📖": "📖",
	"🏰": "🏰",
	"⚔": "⚔",
	"⭐": "⭐",
	//资源tags，注意顺序
	", naturesource": "，自然源泉",
	", patron": "，赞助",
	", gemimbue": "，灌注宝石",
	", magicgems": "，魔法宝石",
	", prismatic": "，棱柱",
	", elementalgems": "，元素宝石",
	", prismaticgems": "，棱柱宝石",
	", element": "，元素",
	", elemental": "，元素知识",
	", primordialgems": "，原始宝石",
	", primordial": "，原始",
	", primaticrunes": "，棱柱符文",
	", elementalrunes": "，元素符文",
	", primordialrunes": "，原始符文",
	", manas": "，法力能量",
	", bed": "，床",
	", t_pets": "，宠物",
	", pets": "，宠物",
	", workspace": "，工作区",
	", furniture": "，家具",
	", shadowsource": "，暗影源泉",
	", spiritsource": "，精神源泉",
	", plantsource": "，植物源泉",
	", firesource": "，火源泉",
	", airsource": "，风源泉",
	", watersource": "，水源泉",
	", earthsource": "，地源泉",
	", lightsource": "，光源泉",
	", potsource": "，药剂源泉",
	", starsource": "，星空源泉",
	", enchantsource": "，附魔源泉",
	", weavesource": "，编织源泉",
	", timesource": "，时间源泉",
	", tricksource": "，诡计源泉",
	", stables": "，马棚",
	", prison": "，监狱",
	", armssource": "，军备源泉",
	", outdoors": "，户外",
	", t_ritual": "，仪式",
	", ritual": "，仪式",
	", poison": "，毒",
	", reagent": "，试剂",
	", herb": "，草药",
	", t_runes": "，符石",
	", skill": "，技能",
	", t_school": "，学派",
	", school": "，学派",
	", stress": "，压力",
	", t_rest": "，休息",
	", rest": "，休息",
	", book": "，典籍",
	", steed": "，骏马",
	", candle": "，蜡烛",
	", t_hall": "，殿堂",
	", hall": "，殿堂",
	", familiar": "，魔宠",
	", magic": "，魔法",
    " Improved": " 已获得提升",
    " Encountered": " 已遭遇",
    ": Competence": ": 学识造诣",
    " (once)": " (一次性)",
    " (Nature)": " (自然)",
    " (Air)": " (风)",
    " (Arcane)": " (奥术)",
    " (Earth)": " (地)",
    " (earth)": " (地)",
    " (Fire)": " (火)",
    " (Light)": " (光)",
    " (Shadow)": " (暗影)",
    " (Spirit)": " (精神)",
    " (Water)": " (水)",
    " (Blood)": " (血)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+) \(([\d\.]+)\%\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\(x([\d\.,]+)\)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\/ ([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)\/\∞$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) hits Wizrobe for ([\d\.]+) damage$/, '$1 击中了 巫师 并造成了 $2 伤害'],
    [/^(.+) hits (.+) for ([\d\.]+) damage$/, '$1 击中了 $2 并造成了 $3 伤害'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	//属性抵抗
	//注：由于源代码翻译，以下会出现汉字替换原英文再汉化的情况
	//从这里开始 ↓↓↓↓↓↓↓↓
	[/^(.+)\simmunities 火$/, '$1 火免疫'],
	[/^(.+)\sresist 火$/, '$1 火抵抗'],
	[/^(.+)\sbonuses 火$/, '$1 火加成'],
	[/^(.+)\shits 火$/, '$1 火命中加成'],
	[/^(.+)\sresist 光$/, '$1 光抵抗'],
	[/^(.+)\sbonuses 光$/, '$1 光加成'],
	[/^(.+)\shits 光$/, '$1 光命中加成'],
	[/^(.+)\sresist 自然$/, '$1 自然抵抗'],
	[/^(.+)\sbonuses 自然$/, '$1 自然加成'],
	[/^(.+)\shits 自然$/, '$1 自然命中加成'],
	[/^(.+)\sresist 精神$/, '$1 精神抵抗'],
	[/^(.+)\sbonuses 精神$/, '$1 精神加成'],
	[/^(.+)\shits 精神$/, '$1 精神命中加成'],
	[/^(.+)\sresist 暗影$/, '$1 暗影抵抗'],
	[/^(.+)\sbonuses 暗影$/, '$1 暗影加成'],
	[/^(.+)\shits 暗影$/, '$1 暗影命中加成'],
	[/^(.+)\sresist 气$/, '$1 气抵抗'],
	[/^(.+)\sbonuses 气$/, '$1 气加成'],
	[/^(.+)\shits 气$/, '$1 气命中加成'],
	[/^(.+)\sresist 水$/, '$1 水抵抗'],
	[/^(.+)\sbonuses 水$/, '$1 水加成'],
	[/^(.+)\shits 水$/, '$1 水命中加成'],
	[/^(.+)\sresist 地$/, '$1 地抵抗'],
	[/^(.+)\sbonuses 地$/, '$1 地加成'],
	[/^(.+)\shits 地$/, '$1 地命中加成'],

	//到这里结束 ↑↑↑↑↑↑↑↑

	[/^(.+)\sresist undead$/, '$1 亡灵抵抗'],
	[/^(.+)\sresist poison$/, '$1 毒素抵抗'],
	[/^(.+)\sresist necrotic$/, '$1 死灵抵抗'],
	[/^(.+)\sbonuses mana$/, '$1 法力加成'],
	[/^(.+)\sresist cold$/, '$1 冰冷抵抗'],
	[/^(.+)\sresist holy$/, '$1 神圣抵抗'],
	[/^(.+)\stohit$/, '$1 命中'],
	[/^(.+)\sdefense$/, '$1 防御'],
	//异常状态抵抗
	//基础
	[/max\s(.+)/, "$1上限"],
	// [/(.+)\srate/, "$1速率"],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^stable ([\d\.]+)$/, '稳定版 $1'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Grand Quest Run Stamina: \-([\d\.]+)\%$/, '大任务运行耐力: -$1%'],
    [/^Grand Quest Run Life: \-([\d\.]+)\%$/, '大任务运行生命值: -$1%'],
    [/^Lillit\'s Cord: ([\d\.]+)\%$/, '莉莉特的丝带: $1%'],
    [/^Jazid\'s Compass: ([\d\.]+)\%$/, '贾兹德的指南针: $1%'],
    [/^Automata: ([\d\.]+)\%$/, '机关人偶: $1%'],
    [/^Loose Cog: ([\d\.]+)\%$/, '松枢轮齿: $1%'],
    [/^Fire Gem: ([\d\.]+)\%$/, '烈焰宝石: $1%'],
    [/^Air Gem: ([\d\.]+)\%$/, '风之宝石: $1%'],
    [/^Water Gem: ([\d\.]+)\%$/, '流水宝石: $1%'],
    [/^Nature Gem: ([\d\.]+)\%$/, '自然宝石: $1%'],
    [/^Wizrobe Defense: ([\d\.]+)\%$/, '巫师防御: $1%'],
    [/^Completion rate: ([\d\.]+)\%$/, '完成率: $1%'],
    [/^Arag Heights ([\d\.]+)\%$/, '阿拉格高地 $1%'],
    [/^running errands ([\d\.]+)\%$/, '跑腿 $1%'],
    [/^Max Active Minions Levels: ([\d\.]+)\%$/, '活跃仆从等级上限: $1%'],
    [/^Next Improvement: ([\d\.]+)\%$/, '下一个提升: $1%'],
    [/^Breath: \-([\d\.]+)\/s$/, '呼吸: -$1/秒'],
    [/^Stress: \-([\d\.]+)\/s$/, '压力: -$1/秒'],
    [/^Fundamental: ([\d\.]+)\/s$/, '本源: $1/秒'],
    [/^Research: ([\d\.]+)\/s$/, '研究: $1/秒'],
    [/^Gold: ([\d\.]+)\/s$/, '金币: $1/秒'],
    [/^Virtue: ([\d\.]+)\/s$/, '善良: $1/秒'],
    [/^Fire: ([\d\.]+)\/s$/, '火: $1/秒'],
    [/^Vigor: ([\d\.]+)\/s$/, '活力: $1/秒'],
    [/^Arcana: ([\d\.]+)\/s$/, '奥术：$1/秒'],
    [/^Barrier Rate: ([\d\.]+)$/, '护盾恢复速度：$1'],
    [/^Mana Rate: ([\d\.]+)$/, '法力恢复速度：$1'],
    [/^Max Barrier: (\d+)$/, '最大护盾：$1'],
    [/^Resting Effect Life: (-?[\d\.]+)$/, '休息生命恢复：$1'],
    [/^Resting Effect Stamina: (-?[\d\.]+)$/, '休息耐力恢复：$1'],
    [/^Resting Effect Stress: (-?[\d\.]+)$/, '休息压力恢复：$1'],
    [/^Resting Effect Vigor: (-?[\d\.]+)$/, '休息活力恢复：$1'],
    [/^Skill Rate: (\d+\%)$/, '技能效率：$1'],
    [/^Water Rate: ([\d\.]+)$/, '水源恢复速度：$1'],
    [/^\+([\d\.]+)\/s \(Downtime\)$/, '停机恢复 +$1/秒'],
    [/^Life: ([\d\.]+)\/s$/, '生命值: $1/秒'],
    [/^Nature Studies Exp: ([\d\.]+)\/s$/, '自然学习经验: $1/秒'],
    [/^Mana: ([\d\.]+)\/s$/, '法力: $1/秒'],
    [/^Dreams: ([\d\.]+)\/s$/, '幻梦: $1/秒'],
    [/^Stamina: ([\d\.]+)\/s$/, '耐力: $1/秒'],
    [/^Prismatic: ([\d\.]+)\/s$/, '棱柱: $1/秒'],
    [/^Wizrobe Exp: ([\d\.]+)\/s$/, '巫师经验值: $1/秒'],
    [/^Magic Beasts Exp: ([\d\.]+)\/s$/, '魔法异兽经验值: $1/秒'],
    [/^Nature Studies Exp: ([\d\.]+)\/s$/, '自然研习经验值: $1/秒'],
    [/^Runic Lore Rate: ([\d\.]+) per ([\d\.]+) amount \(rounded down\) up to ([\d\.]+) \(resulting in ([\d\.]+)\)$/, '符文知识速率：每 $2 加 $1（向下取整），上限为 $3（最终结果为 $4）'],
    [/^Earth Rate: ([\d\.]+)$/, '地元素速率: $1'],
    [/^Herbalism Exp: ([\d\.]+)$/, '草药学经验值: $1'],
    [/^Wizrobe Exp: ([\d\.]+)$/, '巫师经验值: $1'],
    [/^Light Rate: ([\d\.]+)$/, '光速率: $1'],
    [/^Codices Rate: ([\d\.]+)$/, '手稿速率: $1'],
    [/^Scrolls Rate: ([\d\.]+)$/, '卷轴速率: $1'],
    [/^Research Rate: ([\d\.]+)$/, '研究速率: $1'],
    [/^Spellcraft Rate: ([\d\.]+)$/, '法术造诣速率: $1'],
    [/^Star Shard Rate: ([\d\.]+)$/, '星陨碎片速率: $1'],
    [/^Arcana Rate: ([\d\.]+)$/, '奥术速率: $1'],
    [/^Mage Lore Rate: ([\d\.]+)$/, '法师学识速率: $1'],
    [/^Notoriety Rate: ([\d\.]+)$/, '名望速率: $1'],
    [/^Tomes Rate: ([\d\.]+)$/, '典籍速率: $1'],
    [/^Virtue Rate: ([\d\.]+)$/, '善良速率: $1'],
    [/^Dreams Rate: ([\d\.]+)$/, '幻梦速率: $1'],
    [/^Gold Rate: ([\d\.]+)$/, '金币速率: $1'],
    [/^Gold Rate: \-([\d\.]+)$/, '金币速率: -$1'],
    [/^Scrolls ➢ Research Rate: ([\d\.]+)$/, '卷轴 ➢ 研究速率: $1'],
      [/^Pouch \((\d+)\)$/, '小袋子 ($1)'],
  [/^Purse \((\d+)\)$/, '钱包 ($1)'],
    [/^Tomes ➢ Max Arcana: ([\d\.]+)$/, '典籍 ➢ 奥术上限: $1'],
    [/^Spellcraft ➢ Max Spellcraft Level: ([\d\.]+)$/, '法术造诣 ➢ 法术造诣等级上限: $1'],
    [/^Geomancy ➢ Max Earth: ([\d\.]+)$/, '地脉术 ➢ 大地上限: $1'],
    [/^Enchanting ➢ Max Enchanting Power: ([\d\.]+)$/, '附魔 ➢ 附魔力量上限: $1'],
    [/^Max Arcana: ([\d\.]+)$/, '奥术速率: $1'],
    [/^Bones: ([\d\.]+)$/, '骨头: $1'],
    [/^Arcana: ([\d\.]+)$/, '奥术: $1'],
    [/^Evil: ([\d\.]+)$/, '邪恶: $1'],
    [/^Virtue: ([\d\.]+)$/, '善良: $1'],
    [/^Mana: ([\d\.]+)$/, '法力: $1'],
    [/^Evil: \-([\d\.]+)$/, '邪恶: -$1'],
    [/^Virtue: \-([\d\.]+)$/, '善良: -$1'],
    [/^Scribe Scroll Cost Research: \-([\d\.]+)$/, '抄录成本研究: -$1'],
    [/^Floor Space: \-([\d\.]+)$/, '楼层空间: -$1'],
    [/^Rune Stones: ([\d\.]+)$/, '符文石: $1'],
    [/^Charred Chain: ([\d\.]+)$/, '焦烬锁链: $1'],
    [/^Gemstones: ([\d\.]+)$/, '宝石: $1'],
    [/^Stamina: ([\d\.]+)$/, '耐力: $1'],
    [/^Max 🏰Expanded Halls: ([\d\.]+)$/, '🏰扩建殿堂上限: $1'],
    [/^Max Animal Handling: ([\d\.]+)$/, '动物处理上限: $1'],
    [/^Max Magic Beasts: ([\d\.]+)$/, '魔法生物上限: $1'],
    [/^Max Magiphysics: ([\d\.]+)$/, '魔法物理学上限: $1'],
    [/^Max Alchemy: ([\d\.]+)$/, '炼金上限: $1'],
    [/^Max Amulet: ([\d\.]+)$/, '护符上限: $1'],
    [/^Max Shins: ([\d\.]+)$/, '腿部上限: $1'],
    [/^Max Waist: ([\d\.]+)$/, '腰部上限: $1'],
    [/^Max Trinket: ([\d\.]+)$/, '饰品上限: $1'],
    [/^Max Spellcraft: ([\d\.]+)$/, '法术造诣上限: $1'],
    [/^Max Minions: ([\d\.]+)$/, '仆从上限: $1'],
    [/^Max Floor Space: ([\d\.]+)$/, '楼层空间上限: $1'],
    [/^Max Codices: ([\d\.]+)$/, '手稿: $1'],
    [/^Max Inventory: ([\d\.]+)$/, '库存上限: $1'],
    [/^Max Tomes: ([\d\.]+)$/, '典籍上限: $1'],
    [/^Max Back: ([\d\.]+)$/, '背部上限: $1'],
    [/^Max Potions: ([\d\.]+)$/, '药水上限: $1'],
    [/^Max Chest: ([\d\.]+)$/, '胸部上限: $1'],
    [/^Max Dreams: ([\d\.]+)$/, '幻梦上限: $1'],
    [/^Max World Lore: ([\d\.]+)$/, '世界学识上限: $1'],
    [/^Max Weaving: ([\d\.]+)$/, '编织上限: $1'],
    [/^Max Feet: ([\d\.]+)$/, '脚部上限: $1'],
    [/^Max Hands: ([\d\.]+)$/, '手部上限: $1'],
    [/^Max Head: ([\d\.]+)$/, '头部上限: $1'],
    [/^Max Ring: ([\d\.]+)$/, '戒指上限: $1'],
    [/^Max Gold: ([\d\.]+)$/, '金币上限: $1'],
    [/^Research: ([\d\.]+)$/, '研究: $1'],
    [/^Clean Stables Result Gold: ([\d\.]+)$/, '清理马厩最终金币: $1'],
    [/^Do Chores Result Gold: ([\d\.]+)$/, '做家务最终金币: $1'],
    [/^Animal Handling Exp: ([\d\.]+)$/, '驯兽经验: $1'],
    [/^Dreams: ([\d\.]+)$/, '幻梦: $1'],
    [/^Scrolls: ([\d\.]+)$/, '卷轴: $1'],
    [/^Completion time: ([\d\.]+):([\d\.]+):([\d\.]+)$/, '完成时间: $1:$2:$3'],
    [/^Max Research: ([\d\.]+)$/, '研究上限: $1'],
    [/^Notoriety: ([\d\.]+)$/, '名望: $1'],
    [/^Turn delay: ([\d\.]+) seconds$/, '回合延迟: $1 秒'],
    [/^Study Effect Research: ([\d\.]+)$/, '学习影响研究: $1'],
    [/^Resting Effect Dreams: ([\d\.]+)$/, '休息影响幻梦: $1'],
    [/^Run Errands Effect Gold: ([\d\.]+)$/, '跑腿影响金币: $1'],
    [/^Nature Gem: ([\d\.]+)$/, '自然宝石: $1'],
    [/^Arcane Gem: ([\d\.]+)$/, '奥术宝石: $1'],
    [/^Speed: ([\d\.]+)$/, '速度: $1'],
    [/^Tomes: ([\d\.]+)$/, '典籍: $1'],
    [/^Hall Prestige: ([\d\.]+)$/, '殿堂声望: $1'],
    [/^Wizrobe Tohit: ([\d\.]+)$/, '巫师命中: $1'],
    [/^Herbs: ([\d\.]+)$/, '草药: $1'],
    [/^Light Gem: ([\d\.]+)$/, '光明宝石: $1'],
    [/^Ichor: ([\d\.]+)$/, '灵液: $1'],
    [/^Distance: ([\d\.]+)$/, '距离: $1'],
    [/^Earth Gem: ([\d\.]+)$/, '大地宝石: $1'],
    [/^Star Shard: ([\d\.]+)$/, '星陨碎片: $1'],
    [/^Hallsize: ([\d\.]+)$/, '殿堂大小: $1'],
    [/^Trickery Exp: ([\d\.]+)$/, '诡术经验: $1'],
    [/^Gold: ([\d\.]+)$/, '金币: $1'],
    [/^Gold: ([\d\.,]+) \~ ([\d\.,]+)$/, '金币: $1 ~ $2'],
    [/^Gemstones: ([\d\.,]+) \~ ([\d\.,]+)$/, '宝石: $1 ~ $2'],
    [/^🔥Hawthorn Blossom: ([\d\.,]+) \~ ([\d\.,]+)$/, '🔥山楂花: $1 ~ $2'],
    [/^Adamant: ([\d\.,]+) \~ ([\d\.,]+)$/, '合金: $1 ~ $2'],
    [/^Amber Root: ([\d\.,]+) \~ ([\d\.,]+)$/, '琥珀根: $1 ~ $2'],
    [/^\- ([\d\.,]+) \/ ([\d\.,]+) Used$/, '- 已使用 $1 / $2'],
    [/^Amulet \(([\d\.,]+)\/([\d\.,]+)\):$/, '护身符 ($1/$2):'],
    [/^Ring \(([\d\.,]+)\/([\d\.,]+)\):$/, '戒指 ($1/$2):'],
    [/^Aetherhide: ([\d\.,]+) \~ ([\d\.,]+)$/, '以太皮: $1 ~ $2'],
    [/^Cotton: ([\d\.,]+) \~ ([\d\.,]+)$/, '棉花: $1 ~ $2'],
    [/^Bone Dust: ([\d\.,]+) \~ ([\d\.,]+)$/, '骨粉: $1 ~ $2'],
    [/^Basilisk Hide: ([\d\.,]+) \~ ([\d\.,]+)$/, '蜥怪外皮: $1 ~ $2'],
    [/^Dragon Scales: ([\d\.,]+) \~ ([\d\.,]+)$/, '龙鳞: $1 ~ $2'],
    [/^🔥Mayflower: ([\d\.,]+) \~ ([\d\.,]+)$/, '🔥五月花: $1 ~ $2'],
    [/^Herbs: ([\d\.,]+) \~ ([\d\.,]+)$/, '草药: $1 ~ $2'],
    [/^Diamonds: ([\d\.,]+) \~ ([\d\.,]+)$/, '钻石: $1 ~ $2'],
    [/^Bones: ([\d\.,]+) \~ ([\d\.,]+)$/, '骨头: $1 ~ $2'],
    [/^Bodies: ([\d\.,]+) \~ ([\d\.,]+)$/, '躯体: $1 ~ $2'],
    [/^Tomes: ([\d\.,]+) \~ ([\d\.,]+)$/, '典籍: $1 ~ $2'],
    [/^Water Gem: ([\d\.,]+) \~ ([\d\.,]+)$/, '流水宝石: $1 ~ $2'],
    [/^Ichor: ([\d\.,]+) \~ ([\d\.,]+)$/, '灵液: $1 ~ $2'],
    [/^Machinae: ([\d\.,]+) \~ ([\d\.,]+)$/, '机械造物: $1 ~ $2'],
    [/^Rubies: ([\d\.,]+) \~ ([\d\.,]+)$/, '红宝石: $1 ~ $2'],
    [/^Shadow Gem: ([\d\.,]+) \~ ([\d\.,]+)$/, '暗影宝石: $1 ~ $2'],
    [/^Puppets: ([\d\.,]+) \~ ([\d\.,]+)$/, '木偶: $1 ~ $2'],
    [/^Serpent Skin: ([\d\.,]+) \~ ([\d\.,]+)$/, '玄蛇鳞皮: $1 ~ $2'],
    [/^Quicksteel: ([\d\.,]+) \~ ([\d\.,]+)$/, '迅钢: $1 ~ $2'],
    [/^Scrolls: ([\d\.,]+) \~ ([\d\.,]+)$/, '卷轴: $1 ~ $2'],
    [/^Iron: ([\d\.,]+) \~ ([\d\.,]+)$/, '铁: $1 ~ $2'],
    [/^Spider Silk: ([\d\.,]+) \~ ([\d\.,]+)$/, '蛛丝: $1 ~ $2'],
    [/^Leather: ([\d\.,]+) \~ ([\d\.,]+)$/, '皮革: $1 ~ $2'],
    [/^Expanded Halls \(([\d\.,]+)\)$/, '扩建殿堂 ($1)'],
    [/^Great Wing \(([\d\.,]+)\)$/, '巨翼 ($1)'],
    [/^Magic Stables \(([\d\.,]+)\)$/, '魔法马厩 $1'],
    [/^Star Chamber \(([\d\.,]+)\)$/, '星穹密室 ($1)'],
    [/^Wax Candle \(([\d\.,]+)\)$/, '蜡烛 ($1)'],
    [/^Fine-tuned Parts ([\d\.,]+)$/, '精密调校零件 $1'],
    [/^Void ([\d\.,]+)$/, '虚空	 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);