/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Achievement Gotten!": "成就达成!",
    "On": "打开",
    "Off": "关闭",
	//资源tags
	"gemimbue": "灌注宝石",
	"magicgems": "魔法宝石",
	"prismatic": "棱柱",
	"prismaticgems": "棱柱宝石",
	"elementalgems": "元素宝石",
	"element": "元素",
	"elemental": "元素知识",
	"primordialgems": "原始宝石",
	"primordial": "原始",
	"elementalrunes": "元素符文",
	"primaticrunes": "棱柱符文",
	"primordialrunes": "原始符文",
	"manas": "法力能量",
	"bed": "床",
	"t_pets": "宠物",
	"pets": "宠物",
	"workspace": "工作区",
	"furniture": "家具",
	"shadowsource": "暗影源泉",
	"spiritsource": "精神源泉",
	"plantsource": "植物源泉",
	"naturesource": "自然源泉",
	"firesource": "火源泉",
	"airsource": "气源泉",
	"watersource": "水源泉",
	"earthsource": "土源泉",
	"lightsource": "光源泉",
	"potsource": "药剂源泉",
	"starsource": "星空源泉",
	"enchantsource": "附魔源泉",
	"weavesource": "编织源泉",
	"timesource": "时间源泉",
	"tricksource": "诡计源泉",
	"stables": "马棚",
	"prison": "监狱",
	"armssource": "军备源泉",
	"outdoors": "户外",
	"patron": "赞助",
	"t_ritual": "仪式",
	"ritual": "仪式",
	"poison": "毒",
	"herb": "草药",
	"reagent": "试剂",
	"t_runes": "符石",
	"skill": "技能",
	"t_school": "学派",
	"school": "学派",
	"stress": "压力",
	"t_rest": "休息",
	"rest": "休息",
	"book": "典籍",
	"steed": "骏马",
	"candle": "蜡烛",
	"t_hall": "殿堂",
	"hall": "殿堂",
	"familiar": "魔宠",
	"magic": "魔法",

	//药剂名：
	"sip of gold": "财富药剂",
	"drip of mana": "生命分流",
	"echoing flask": "回声药水",
	"god's blood": "神之血液",
	"godspeed": "神速药剂",
	"healing potion": "治疗药水",
	"phial of skillfulness": "学识药水",
	"philter of clarity": "灵感药水",
	"potion of bull's tenacity": "牛的力量",
	"potion of monster's stamina": "怪物级耐力药水",
	"remedy": "十全大补抗性药",
	"tincture of limberness": "麻痹解除",
	"adamant salve": "合金药剂",
	"portion of waterbreathing": "水下呼吸药剂",
	'': '',
	
	//药水说明：
	"A master\'s skill in liquid form": "液态化的技能点数",
	"Amplifies even significantly muffled sounds.": "即使细碎的低语也能放大。",
	"Converts passive information into short-term benefit": "让被动获取的资源派上大用场，厚积薄发！",	
	"Purchase Cost": "解锁花费",
	"Raw mana injected right into the veins of a mage can allow for sustained casting, if one disregards the side-effects": "也许把未经提炼的法力注入静脉能提高法力速率，这可能会有点痒	（译者注：不要往自己静脉打奇怪的东西啊！）",
	"Temporarily grants you an impeccable ability to acquire valuables.": "获得一段时间的研究经费支持，包括宝石碎片",
	"This reddish potion causes a surge of energy in the imbiber, at the expense of health": "这种略带红色的药剂会让身体超载",
    "Removes most forms of inisidious motion impairment.": "治疗大多数行动不便的症状",
	"Cures most common ailments and fortifies the body.": "治疗大多数常见的小毛病并增强体质",
    "Unusually, prepared by baking special herbs into a brownie.": "这些草药居然能用来做巧克力蛋糕",
	
	//异常效果：
	"sick": "疾病",
	"fear": "恐惧",
	"enrage": "狂化",
	"charmed": "魅惑",
	"quake": "失衡",
	"quell": "压制",
	"sacked": "束缚",
	
	
	//简单的词语：
	
	"When used": "效果",
	"potion": "药剂",
	"action cure: paralysis,enrage,charmed,fear,silence,sick": "抵抗效果：麻痹，狂化，魅惑，恐惧，沉默，疾病",
	"action targets: self": "指定目标：自己",
	"Targets: all": "指定目标：全部",
	"Targets: allies": "指定目标：盟友",
	"Targets: enemies": "指定目标：敌方",
	"Applies": "效果",
	"Attack": "攻击",
	"Attack hit": "攻击命中",
	"tohit": "命中率",
	" tohit": "命中率",
	"Damage": "伤害",
	"Duration": "持续时间",
	"Effects": "影响",
	"Results": "结果",
	"Kind": "属性种类",
	"Kind: air": "气属性",
	"Kind: chaos": "混沌（虚空）属性",
	"Kind: earth": "地属性",
	"Kind: fire": "火属性",
	"Kind: light": "光属性",
	"Kind: mana": "奥术属性",
	"Kind: nature": "自然属性",
	"Kind: shadow": "暗影属性",
	"Kind: spirit": "精神属性",
	"Kind: water": "水属性",

    //部分装备名称：
	
	"loop": "臂带",
	"band": "手环",
	" hide jerkin": "皮坎肩",
	" hide hat": "皮帽",
	" hide band": "皮指环",
	" hide loop": "皮指绳结",
	" hide girdle": "皮腰带",
	" hide gloves": "皮手套",
	" hide helm": "皮头盔",
	" hide greaves": "皮胫甲",
	" hide padded armor": "皮厚甲",
	" hide 护身符": "皮护身符",
	" hide 戒指": "皮戒指",
	
	"adamantine 护身符": "合金护身符",
	"adamantine 戒指": "合金戒指",
	"adamantine axe": "合金斧子",
	"adamantine band": "合金指环",
	"adamantine battleaxe": "合金战斧",
	"adamantine boots": "合金靴子",
	"adamantine cane": "合金手杖",
	"adamantine cap": "合金帽子",
	"adamantine chainmail": "合金锁甲",
	"adamantine cincture": "合金腰甲",
	"adamantine club": "合金短棒",
	"adamantine collar": "合金衣领",
	"adamantine conical helm": "合金项圈",
	"adamantine girdle": "合金腰带",
	"adamantine greatstaff": "合金法杖",
	"adamantine greaves": "合金胫甲",
	"adamantine hat": "合金帽子",
	"adamantine helm": "合金头盔",
	"adamantine knife": "合金小刀",
	"adamantine longsword": "合金长剑",
	"adamantine loop": "合金指绳结",
	"adamantine mace": "合金狼牙棒",
	"adamantine necklace": "合金项链",
	"adamantine pendant": "合金吊坠",
	"adamantine plate mail": "合金板甲",
	"adamantine rod": "合金魔杖",
	"adamantine spear": "合金长矛",
	"adamantine staff": "合金棍子",
	"adamantine sword": "合金剑",
	"adamantine wand": "合金魔棒",
	"adamantine warhammer": "合金战锤",
	"adamantine wings": "合金翼甲",
	
	
	//怪物名（准备中）
	"basilisk": "蛇怪",
	
	
	//资源group
	"books": "典籍",
	"runes": "符石",
	"necromancy": "死灵术",
	"gems": "宝石",
	"puppets": "木偶",
	"other": "其它",
	"Actions": "行动",
	"Tasks": "任务",
	"Upgrades": "升级",

	"stamina": "耐力",
	"Stamina": "耐力",
	"life": "生命",
	"Life": "生命",
	"Name": "名字",
	"Title": "头衔",
	"Notoriety": "名望",
	"Level": "等级",
	"Experience": "经验",
	"Virtue : Evil": "善良：邪恶",
	"Skill Points": "技能点",
	"Rest": "休息",
	"Mount": "坐骑",
	"mount": "坐骑",
	"Distance": "距离",
	"Classes": "阶级",
	"Progress Cost": "进度成本",
	"Results": "结果",
	"Cost": "成本",
	"Effects": "效果",
	"Focus": "专注",
	"Save": "保存",
	"Load": "读取",
	"Get Save": "下载存档",
	"Hall Save": "下载殿堂存档",
	"[Load Save]": "[加载存档]",
	"Wipe Wizard": "删除角色",
	"Wipe Hall Save": "删除殿堂存档",
	"Wizard's Hall": "巫师殿堂",
	"Find": "查找",
	"Hide Maxed": "隐藏已满",
	'\n			Train': '训练',
	'\n			Stop': '停止',
	'Space': '空间',
	'Furnishing': '家具',
	'Owned': '已拥有',
	'Maxed': '达上限',
	'Unowned': '未拥有',
	'Blocked': '已锁定',
	'Home': '家园',
	'Werry': '位面',
	'Sort Level': '按等级排序',
	'Complete': '已完成',
	'Dungeon': '地下城',
	'Explore': '探索',
	'Enter': '进入',
	'Retreat': '撤退',
	'Luck': '幸运值',
	"defense": '护甲',
	'Defense': '防御',
	'Dodge': '闪避',
	'Damage Bonus': '伤害加成',
	'Bonus Damage': '加成伤害',
	'Hit Bonus': '命中加成',
	'Speed': '速度',
	'Weapon': '武器',
	'Resists': '抵抗',
	'Immunities': '免疫',
	'fire': '火',
	'water': '水',
	'air': '气',
	'earth': '地',
	'light': '光',
	'shadow': '暗影',
	'arcane': '奥术',
	'physical': '物理',
	'natural': '自然',
	'poison': '毒素',
	'disease': '疾病',
	'Stop All': '全部停止',
	'Clear': '清除',
	'event': '事件',
	'unlock': '解锁',
	'loot': '拾取',
	'combat': '战斗',
	'Modifications': '修订',
	'Learn': '学习',
	'Cast': '施放',
	'Memorize': '记忆',
	'Memorized': '已记忆',
	'Remove': '移除',
	'No space remaining. Sell items or find a new Home.\n			': '没有剩余空间。 出售物品或找到新家。',
	'If your max gold is not enough to buy a new home, free space for more chests.': '如果你达到金币上限都买不起新家，腾出点地方买更多的箱子吧。',
	'\n		Roll-over Item and hold {Shift} + {Number} to assign quickslot.': '滚动物品并按住{Shift} + {数字}可以分配快速插槽。',
	'\n		Press {Number} again to use quickslot Item.\n	': '再次按{数字}以使用快速插槽物品。',
	"Enchantment levels on an Item cannot exceed Item's enchant slots.": '物品的附魔等级不能超过物品的附魔槽。',
	'animation': '机械',
	'nature': '自然',
	'spirit': '精神',
	"mana": "法力",
	'charms': '魅惑',
	'astral': '星空',
	'Craft': '制造',
	'right': '右',
	'left': '左',
	'ring': '戒指',
	'fingers': '手指',
	'neck': '颈部',
	'shins': '腿',
	'waist': '腰',
	'hands': '手',
	'head': '头',
	'back': '背部',
	'feet': '脚',
	'chest': '胸',
	'trinket': '饰品',
	'Brew': '调制',
	'Resume': '恢复',
	'Enchant': '附魔',
	'Need': '需求',
	'Purchase Cost': '采购成本',
	'max activity': '行动上限',
	"max magicgems": "魔法宝石上限",
	"max prismatic": "棱柱上限",
	"prismatic rate": "棱柱速率",
	"max prismaticgems": "棱柱宝石上限",
	"max elementalgems": "元素宝石上限",
	"max element": "元素上限",
	"max elemental": "元素上限",
	"elemental 经验值": "元素知识 经验值",
	"activity 经验值": "行动 经验值",
	"elemental rate": "元素知识速率",
	"max primordialgems": "原始宝石上限",
	"max primordial": "原始上限",
	"max elementalrunes": "元素符文上限",
	"max primaticrunes": "棱柱符文上限",
	"max primordialrunes": "原始符文上限",
	"max manas": "法力能量上限",
	"manas rate": "法力能量速率",
	"max t_runes": "符石上限",
	"max spelllist": "法术列表上限",
	"max inventory": "物品栏上限",
	"max candle": "蜡烛上限",
	"max stress": "压力上限",
	"stress rate": "压力速率",
	"Max": "上限",
	"Buy": "购买",
	"Sell": "出售",
	"home": "家园",
	'Flee': '逃跑',
	'None': '无',
	'Cancel': '取消',
	'Confirm': '确认',
	'Skip Warning': '跳过警告',
	'Locks': '锁定',
	'LOOT': '掠夺',
	'RETREAT': '撤退',
	'Alternate Wizard classes of this tier will be locked.': '这一层的其它巫师职业将被锁定。',
	'This action is not reversible. Continue?': '这个动作不可逆，是否确定？（译者注：一般都有一些负面效果，请先导出存档。）',
    "(Full)": "(完整)",
    "Auto-Save": "自动保存",
    "Close": "关闭",
    "clean stables": "清理马厩",
    "Clean Stables": "清理马厩",
    "Combat": "战斗",
    "LOADING DATA...": "加载数据中...",
    "player": "玩家",
    "main": "首页",
    "Idle": "空闲",
    "gold": "金币",
    "basic": "基础",
    "Actions will only be performed if their outputs can be fully collected": "仅当收益可全额收取时，才会执行对应行动",
    "barrier": "屏障",
    "Body": "身躯属性",
    "Compact Mode": "紧凑模式",
    "Dark Mode": "深色模式",
    "Display total task effects": "显示全部任务效果",
    "Effects:": "效果：",
    "Elemental": "元素系",
    "Event": "活动事件",
    "Expand Resource Rate": "展开资源倍率",
    "extra stats": "额外属性",
    "Fast-forward": "快进加速",
    "Fastforward speed": "快进速度",
    "Fundamental Energies": "本源能量",
    "Gameplay adjustments": "玩法调整",
    "It's stable employment.": "稳定挂机收益",
    "Loot": "战利品",
    "Maximized efficiency mode": "极致效率模式",
    "Periodically save game to storage. Game is saved to Browser storage by default.": "定期将游戏存档至本地存储，默认存档至浏览器缓存",
    "pouch": "小袋子",
    "Press {Number} again to use quickslot Item.": "再次按下对应数字键，即可使用快捷栏物品",
    "Primal": "原始本源",
    "Prismatic Energies": "七彩元能",
    "Reddit": "Reddit社区",
    "relax": "休息",
    "Relax": "休息",
    "Resting": "休息中",
    "Results:": "结果：",
    "Roll-over Item and hold {Shift} + {Number} to assign quickslot.": "鼠标悬停物品并按住Shift+数字键，可设置快捷栏",
    "Shows remaining costs to pay and resources to acquire until next completion (for tasks with completion time of more than 1 second)": "显示距任务完成还需消耗的资源与剩余时长（适用于耗时超1秒的任务）",
    "Smooth bars": "平滑进度条",
    "Specialties & Menaces": "专长与负面特质",
    "Speedup factor for fast-forward feature. It is not recommended to set it above 25, depending on your PC performance.": "快进功能倍率，建议不要超过25，具体视电脑性能而定",
    "Starting Out": "新手起步",
    "Storage": "仓库存储",
    "stored time": "已缓存时长",
    "Test Site": "测试服",
    "Tooltip Stats": "悬浮提示属性",
    "Used to hide and unhide entries. This setting is retained between characters.": "用于隐藏/显示条目，设置对所有角色永久生效",
    "vigor": "活力",
    "Warning! This can prevent you from fully filling your resources to max, but will prevent wastefully underpoducing.": "警告！该设置可能导致资源无法堆满上限，但可避免产量不足造成浪费",
    "Wizard life-force.": "法师生命之力",
    "Working from home.": "在家里工作。",
    "Endurance": "耐力",
    "Gold": "金币",
    "Gold coins.": "金币。",
    "Keep your money safe.": "保管你的财富资产。",
    "Modifications:": "属性改动：",
    "Pouch": "小袋子",
    "Seems a tad pricey for a bag.": "这个背包定价略显偏高。",
    "Stored Time": "离线存储时长",
    "Time since you last checked in. Can be used to speed up the game.": "距上次登录的离线时长，可用于加速游戏进度。",
    "Used to mark and unmark entries as favourites. This setting is retained between characters.": "用于将条目设为/取消收藏，设置全角色通用保留。",
    "Vigor": "活力",
    "Where does time go when you aren't looking?": "离线期间时间仍在悄然流逝。",
    "Your capacity for short-term exertions.": "短时间爆发负重与行动耐力上限。",
    "Displays your active and waiting tasks in greater detail.": "更详细地展示当前进行中与待执行任务。",
    "Show calculated resource income from modified rate R, converters C, running tasks T, and buffs B.": "显示由修正倍率R、转化器C、运行任务T及增益buff B共同计算得出的资源收益。",
    "relaxing": "休息中",
    "A novice can get by with very basic scrolls, hopefully you won't need any of the pricier ones.": "新手只用基础卷轴就能过渡，希望你无需用到高价卷轴。",
    "buy scroll": "购买卷轴",
    "Buy Scroll": "购买卷轴",
    "Materials": "材料",
    "A tattered scroll": "一个破旧卷轴",
    "Apprenticeship": "学徒之路",
    "Class Unlocked: Apprenticeship": "职业已解锁：学徒之路",
    "knowledge": "知识",
    "research": "研究",
    "Research": "研究",
    "Research into the Arcane.": "奥术学识研究",
    "Research Rate: 0.005": "研究速率：0.005",
    "Scroll of arcane lore.": "奥术学识卷轴",
    "scrolls": "卷轴",
    "Scrolls": "卷轴",
    "Study": "学习",
    "study": "学习",
    "You buy a strange scroll from a travelling peddler. If you could only decipher the cryptic symbols.": "你从流浪商人手中买下一卷神秘卷轴，唯独无法解读上面晦涩的符文。",
    "Study arcane scrolls.": "学习奥术卷轴。",
    "Use stored time to speed up the game": "利用储存的时间来加快游戏进程。",
    "studying scrolls": "学习卷轴",
    "🛠️Evil\n🛠️Virtue\n🛠️Neutrality": "🛠️邪恶\n🛠️善良\n🛠️中立",
    "3x Glossary Entries on Mechanics Unlocked": "3条游戏机制术语词条已解锁",
    "After paying a small fee, you became apprenticed to a local wizard.": "缴纳少量费用后，你拜入当地一位法师门下成为学徒",
    "Apprentice": "学徒",
    "Become an apprentice.": "成为学徒",
    "Class": "职业",
    "Common way to carry coins.": "存放金币的常用容器",
    "Disables:": "已禁用：",
    "do chores": "做家务",
    "Do Chores": "做家务",
    "Equipment": "装备",
    "glossary": "术语图鉴",
    "alcove": "僻静小屋",
    "purse": "钱包",
    "Purse": "钱包",
    "run errands": "跑腿",
    "Run Errands": "跑腿",
    "mage lore": "法师学识",
    "skills": "技能",
    "Standard apprentice work.": "学徒的日常本职工作",
    "Upgrade Unlocked: purse": "升级项目已解锁：钱袋",
    "ichor": "灵液",
    "🔥hawthorn blossom": "🔥山楂花",
    "Abyssal Depths: First Layer": "深渊之境：第一层",
    "adventure": "冒险",
    "air gem": "风之宝石",
    "Arag Heights": "阿拉格高地",
    "Arag Wastes": "阿拉格荒原",
    "arcana": "奥术秘能",
    "arcane gem": "奥术宝石",
    "Auto Focus": "自动专注",
    "Barren mountains on the coast of Arazor.": "阿拉佐尔海岸的荒芜群山",
    "Basilisk Hide": "蜥怪外皮",
    "Below Mt. Gorborung": "戈尔博隆山脚下",
    "beltane 🔥": "🔥贝尔坦节",
    "bestiary": "怪物图鉴",
    "blood gem": "鲜血宝石",
    "bodies": "躯体",
    "bone dust": "骨粉",
    "bones": "骨头",
    "Charred Keep": "焦黑要塞",
    "Clash": "交锋对决",
    "codices": "古籍秘卷",
    "Companion:": "同伴：",
    "Complete to discover": "完成即可解锁发现",
    "constructs": "构装造物",
    "Corivar's Castle Courtyard": "科里瓦尔城堡庭院",
    "Desilla was known as much for her entertainments as her ruthlessness.": "德茜拉既以纵情享乐闻名，也以冷酷无情著称。",
    "Desilla's Grotto": "德茜拉洞窟",
    "dreams": "幻梦",
    "earth gem": "大地宝石",
    "earth runes": "大地符文",
    "Elemental Rift": "元素裂隙",
    "Eryl Eyot": "艾瑞尔小岛",
    "esoteric": "玄奥秘术",
    "Explore Treffil Wood": "探索特雷菲尔林地",
    "Fazbit's Workshop": "法兹比特工坊",
    "fire gem": "烈焰宝石",
    "fire runes": "烈焰符文",
    "Fire-cursed Shack": "烈焰诅咒囚屋",
    "fly": "飞行",
    "Fly": "飞行",
    "Fly on the winds.": "乘风翱翔",
    "gemstones": "宝石晶矿",
    "Genezereth": "吉尼泽瑞斯",
    "Goblin Camp": "哥布林营地",
    "Hall Of Ages": "岁月殿堂",
    "Haunted Manor": "闹鬼庄园",
    "herbs": "草药",
    "In all the world, the most enjoyable place to die.": "世间最令人安然的归宿之地",
    "light gem": "光明宝石",
    "Lillit's Spring": "莉莉特之泉",
    "Locale": "地域",
    "Loot:": "战利品：",
    "machinae": "机械造物",
    "materials": "材料",
    "Max Charms: 0.5 per 1 amount (rounded down) up to 2 (resulting in 1)": "符咒上限：每1份资源提升0.5点（向下取整），上限2点（最终为1）",
    "May Meadow": "五月草原",
    "Mount Gorborung": "戈尔博隆山",
    "Mount:": "坐骑：",
    "nature gem": "自然宝石",
    "Ogre Cavern": "食人魔洞穴",
    "On First Completion:": "首次完成奖励：",
    "Orc Camp": "兽人营地",
    "Peregrination": "四方游历",
    "Pidwig's Cove": "皮德维格海湾",
    "potion base": "药剂基底",
    "potions": "药剂",
    "Rithel": "里塞尔",
    "Ruined Crypt": "破败墓穴",
    "Rumors say that deep in the woods, there is a shack once inhabited by a wizard obsessed with fire. He has not been seen for years and terrible heat can be felt emanating from the place": "传闻密林深处有一间小屋，曾住着一位痴迷烈焰的法师。他已多年不见踪影，屋内却始终散发出骇人的热浪",
    "rune stones": "符文石",
    "Sands Of Orrem": "奥瑞姆沙海",
    "Seredite Temple": "塞瑞德神庙",
    "shadow gem": "暗影宝石",
    "Site Of Learning, Dungeon": "学识之地 · 地牢",
    "Skittering Caverns": "蠕行洞穴",
    "sleeping": "沉睡",
    "souls": "灵魂",
    "spellcraft": "法术造诣",
    "spells": "法术",
    "spirit gem": "圣灵宝石",
    "star shard": "星陨碎片",
    "Stony Hills": "石丘旷野",
    "tempus": "时序之力",
    "The Catacrypts": "地下古墓群",
    "The Great Bog": "大沼泽",
    "The Lost Menagerie": "失落异兽园",
    "The Unstable Spire": "不稳尖塔",
    "They say the roots of the mountain extend deeper than its heights.": "传言此山根基深埋地底，远比山体巍峨更高深",
    "Title: Lightless": "称号：无光者",
    "tomes": "典籍",
    "Training Grounds": "训练场",
    "Treffil Woods Edges": "特雷菲尔林地边缘",
    "Under Den": "巢穴下层",
    "Veldran's Storehouse": "威尔德伦仓库",
    "Veldran's Wreck": "威尔德伦残骸",
    "Village Fields": "村庄田野",
    "void": "虚空",
    "water gem": "流水宝石",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Po": "袋子",
    "Re": "休息",
    "CS": "清理",
    "Mythic": "神话",
    "Legendary": "传说",
    "Epic": "史诗",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Common": "普通",
    "SPD": "速度",
    "ATK": "攻击",
    "ARM": "护甲",
    "Lvl": "等级",
    "Unlock": "解锁",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "↑": "↑",
    "↑↓": "↑↓",
    "↓": "↓",
    "🌟": "🌟",
    "💀💀": "💀💀",
    "💀💀💀": "💀💀💀",
    "💀💀💀💀💀": "💀💀💀💀💀",
    "🔍": "🔍",
    "🔒": "🔒",
    "💀💀💀💀": "💀💀💀💀",
    "💀💀💀💀💀💀": "💀💀💀💀💀💀",
    "🦴🦴🦴": "🦴🦴🦴",
    "💀": "💀",
    "🔥": "🔥",
    "◄": "◄",
    "▶": "▶",
    "▼": "▼",
    "⚙": "⚙",
    "\xa0X\xa0": "X",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "Next at ": "下一个在 ",
    "Show Milestone Popups: ": "显示里程碑弹窗：",
    "Made by ": "作者 ",
	"🌳": "🌳",
	"📖": "📖",
	"🏰": "🏰",
	"⚔": "⚔",
    "⭐": "⭐",
    "❄️": "❄️",
    "\n			Next Improvement: ": "下一次提升：",
    "\n\n\t\texp: ": "经验：",
    "Space: ": "空间：",
    "mana: ": "法力：",
    "fire: ": "火：",
    "air: ": "气：",
    "water: ": "水：",
	'earth: ': '地：',
	'light: ': '光：',
	'shadow: ': '暗影：',
	'arcane: ': '奥术：',
	'physical: ': '物理：',
	'natural: ': '自然：',
	'poison: ': '毒素：',
	'disease: ': '疾病：',
	'Max Levels: ': '等级上限：',
	'Power: ': '能量：',
	'Slot: ': '插槽：',
	'upgrade Unlocked: ': '升级解锁：',
	'action Unlocked: ': '行动解锁：',
	'resource Unlocked: ': '资源解锁：',
	'class Unlocked: ': '职业解锁：',
	'Unlocked: ': '解锁：',
	'locale Unlocked: ': '地点解锁：',
	'furniture Unlocked: ': '家具解锁：',
	'skill Unlocked: ': '技能解锁：',
	'home Unlocked: ': '住房解锁：',
	'dungeon Unlocked: ': '地下城解锁：',
	'potion Unlocked: ': '药剂解锁：',
	'enchant Unlocked: ': '附魔解锁：',
	'spell Unlocked: ': '法术解锁：',
	'monster Unlocked: ': '怪物解锁：',
	'Title Earned: ': '获得头衔：',
	'title: ': '头衔：',
	'max: ': '上限：',
    "Task Unlocked: ": "任务已解锁：",
    "Resource Unlocked: ": "资源已解锁: ",
    "Skill Unlocked: ": "技能已解锁：",
    "Home Unlocked: ": "家园已解锁：",
    "Level: ": "等级: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "❄️": "❄️",
    '🎃': '🎃',
	"🌳": "🌳",
	"📖": "📖",
	"🏰": "🏰",
	"⚔": "⚔",
	"⭐": "⭐",
	//资源tags，注意顺序
	", naturesource": "，自然源泉",
	", patron": "，赞助",
	", gemimbue": "，灌注宝石",
	", magicgems": "，魔法宝石",
	", prismatic": "，棱柱",
	", elementalgems": "，元素宝石",
	", prismaticgems": "，棱柱宝石",
	", element": "，元素",
	", elemental": "，元素知识",
	", primordialgems": "，原始宝石",
	", primordial": "，原始",
	", primaticrunes": "，棱柱符文",
	", elementalrunes": "，元素符文",
	", primordialrunes": "，原始符文",
	", manas": "，法力能量",
	", bed": "，床",
	", t_pets": "，宠物",
	", pets": "，宠物",
	", workspace": "，工作区",
	", furniture": "，家具",
	", shadowsource": "，暗影源泉",
	", spiritsource": "，精神源泉",
	", plantsource": "，植物源泉",
	", firesource": "，火源泉",
	", airsource": "，气源泉",
	", watersource": "，水源泉",
	", earthsource": "，土源泉",
	", lightsource": "，光源泉",
	", potsource": "，药剂源泉",
	", starsource": "，星空源泉",
	", enchantsource": "，附魔源泉",
	", weavesource": "，编织源泉",
	", timesource": "，时间源泉",
	", tricksource": "，诡计源泉",
	", stables": "，马棚",
	", prison": "，监狱",
	", armssource": "，军备源泉",
	", outdoors": "，户外",
	", t_ritual": "，仪式",
	", ritual": "，仪式",
	", poison": "，毒",
	", reagent": "，试剂",
	", herb": "，草药",
	", t_runes": "，符石",
	", skill": "，技能",
	", t_school": "，学派",
	", school": "，学派",
	", stress": "，压力",
	", t_rest": "，休息",
	", rest": "，休息",
	", book": "，典籍",
	", steed": "，骏马",
	", candle": "，蜡烛",
	", t_hall": "，殿堂",
	", hall": "，殿堂",
	", familiar": "，魔宠",
	", magic": "，魔法",
    " Improved": " 已获得提升",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+) \(([\d\.]+)\%\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\(x([\d\.,]+)\)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\/ ([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)\/\∞$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) hits (.+) for ([\d\.]+) damage$/, '$1 击中了 $2 并造成了 $3 伤害'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	//属性抵抗
	//注：由于源代码翻译，以下会出现汉字替换原英文再汉化的情况
	//从这里开始 ↓↓↓↓↓↓↓↓
	[/^(.+)\simmunities 火$/, '$1 火免疫'],
	[/^(.+)\sresist 火$/, '$1 火抵抗'],
	[/^(.+)\sbonuses 火$/, '$1 火加成'],
	[/^(.+)\shits 火$/, '$1 火命中加成'],
	[/^(.+)\sresist 光$/, '$1 光抵抗'],
	[/^(.+)\sbonuses 光$/, '$1 光加成'],
	[/^(.+)\shits 光$/, '$1 光命中加成'],
	[/^(.+)\sresist 自然$/, '$1 自然抵抗'],
	[/^(.+)\sbonuses 自然$/, '$1 自然加成'],
	[/^(.+)\shits 自然$/, '$1 自然命中加成'],
	[/^(.+)\sresist 精神$/, '$1 精神抵抗'],
	[/^(.+)\sbonuses 精神$/, '$1 精神加成'],
	[/^(.+)\shits 精神$/, '$1 精神命中加成'],
	[/^(.+)\sresist 暗影$/, '$1 暗影抵抗'],
	[/^(.+)\sbonuses 暗影$/, '$1 暗影加成'],
	[/^(.+)\shits 暗影$/, '$1 暗影命中加成'],
	[/^(.+)\sresist 气$/, '$1 气抵抗'],
	[/^(.+)\sbonuses 气$/, '$1 气加成'],
	[/^(.+)\shits 气$/, '$1 气命中加成'],
	[/^(.+)\sresist 水$/, '$1 水抵抗'],
	[/^(.+)\sbonuses 水$/, '$1 水加成'],
	[/^(.+)\shits 水$/, '$1 水命中加成'],
	[/^(.+)\sresist 土$/, '$1 土抵抗'],
	[/^(.+)\sbonuses 土$/, '$1 土加成'],
	[/^(.+)\shits 土$/, '$1 土命中加成'],

	//到这里结束 ↑↑↑↑↑↑↑↑

	[/^(.+)\sresist undead$/, '$1 亡灵抵抗'],
	[/^(.+)\sresist poison$/, '$1 毒素抵抗'],
	[/^(.+)\sresist necrotic$/, '$1 死灵抵抗'],
	[/^(.+)\sbonuses mana$/, '$1 法力加成'],
	[/^(.+)\sresist cold$/, '$1 冰冷抵抗'],
	[/^(.+)\sresist holy$/, '$1 神圣抵抗'],
	[/^(.+)\stohit$/, '$1 命中'],
	[/^(.+)\sdefense$/, '$1 防御'],
	//异常状态抵抗
	//基础
	[/max\s(.+)/, "$1上限"],
	// [/(.+)\srate/, "$1速率"],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^stable ([\d\.]+)$/, '稳定版 $1'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Completion rate: ([\d\.]+)\%$/, '完成率: $1%'],
    [/^Arag Heights ([\d\.]+)\%$/, '阿拉格高地 $1%'],
    [/^running errands ([\d\.]+)\%$/, '跑腿 $1%'],
    [/^Next Improvement: ([\d\.]+)\%$/, '下一个提升: $1%'],
    [/^Stress: \-([\d\.]+)\/s$/, '压力: -$1/秒'],
    [/^Research: ([\d\.]+)\/s$/, '研究: $1/秒'],
    [/^Gold: ([\d\.]+)\/s$/, '金币: $1/秒'],
    [/^Virtue: ([\d\.]+)\/s$/, '善良: $1/秒'],
    [/^Fire: ([\d\.]+)\/s$/, '火: $1/秒'],
    [/^Vigor: ([\d\.]+)\/s$/, '活力: $1/秒'],
    [/^Life: ([\d\.]+)\/s$/, '生命值: $1/秒'],
    [/^Stamina: ([\d\.]+)\/s$/, '耐力: $1/秒'],
    [/^Prismatic: ([\d\.]+)\/s$/, '棱柱: $1/秒'],
    [/^Wizrobe Exp: ([\d\.,]+)$/, '巫师经验值: $1'],
    [/^Research Rate: ([\d\.,]+)$/, '研究速率: $1'],
    [/^Arcana Rate: ([\d\.,]+)$/, '奥术速率: $1'],
    [/^Mage Lore Rate: ([\d\.,]+)$/, '法师学识速率: $1'],
    [/^Max Arcana: ([\d\.,]+)$/, '奥术速率: $1'],
    [/^Virtue: ([\d\.,]+)$/, '善良: $1'],
    [/^Stamina: ([\d\.,]+)$/, '耐力: $1'],
    [/^Max Gold: ([\d\.,]+)$/, '金币上限: $1'],
    [/^Research: ([\d\.,]+)$/, '研究: $1'],
    [/^Scrolls: ([\d\.,]+)$/, '卷轴: $1'],
    [/^Completion time: ([\d\.,]+):([\d\.,]+):([\d\.,]+)$/, '完成时间: $1:$2:$3'],
    [/^Max Research: ([\d\.,]+)$/, '研究上限: $1'],
    [/^Notoriety: ([\d\.,]+)$/, '名望: $1'],
    [/^Speed: ([\d\.,]+)$/, '速度: $1'],
    [/^Tomes: ([\d\.,]+)$/, '典籍: $1'],
    [/^Distance: ([\d\.,]+)$/, '距离: $1'],
    [/^Earth Gem: ([\d\.,]+)$/, '大地宝石: $1'],
    [/^Gold: ([\d\.,]+)$/, '金币: $1'],
    [/^Gold: ([\d\.,]+) \~ ([\d\.,]+)$/, '金币: $1 ~ $2'],
    [/^Gemstones: ([\d\.,]+) \~ ([\d\.,]+)$/, '宝石: $1 ~ $2'],
    [/^Adamant: ([\d\.,]+) \~ ([\d\.,]+)$/, '合金: $1 ~ $2'],
    [/^Amber Root: ([\d\.,]+) \~ ([\d\.,]+)$/, '琥珀根: $1 ~ $2'],
    [/^Aetherhide: ([\d\.,]+) \~ ([\d\.,]+)$/, '以太皮: $1 ~ $2'],
    [/^Cotton: ([\d\.,]+) \~ ([\d\.,]+)$/, '棉花: $1 ~ $2'],
    [/^Ichor: ([\d\.,]+) \~ ([\d\.,]+)$/, '灵液: $1 ~ $2'],
    [/^Iron: ([\d\.,]+) \~ ([\d\.,]+)$/, '铁: $1 ~ $2'],
    [/^Leather: ([\d\.,]+) \~ ([\d\.,]+)$/, '皮革: $1 ~ $2'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);